import { CountryOption, ProfessionalDomain } from './types';

export const COUNTRIES: CountryOption[] = [
  { id: 'global', name: 'International / Global', flag: '🌐' },
  { id: 'af', name: 'Afghanistan', flag: '🇦🇫' },
  { id: 'al', name: 'Albania', flag: '🇦🇱' },
  { id: 'dz', name: 'Algeria', flag: '🇩🇿' },
  { id: 'ad', name: 'Andorra', flag: '🇦🇩' },
  { id: 'ao', name: 'Angola', flag: '🇦🇴' },
  { id: 'ag', name: 'Antigua and Barbuda', flag: '🇦🇬' },
  { id: 'ar', name: 'Argentina', flag: '🇦🇷' },
  { id: 'am', name: 'Armenia', flag: '🇦🇲' },
  { id: 'au', name: 'Australia', flag: '🇦🇺' },
  { id: 'at', name: 'Austria', flag: '🇦🇹' },
  { id: 'az', name: 'Azerbaijan', flag: '🇦🇿' },
  { id: 'bs', name: 'Bahamas', flag: '🇧🇸' },
  { id: 'bh', name: 'Bahrain', flag: '🇧🇭' },
  { id: 'bd', name: 'Bangladesh', flag: '🇧🇩' },
  { id: 'bb', name: 'Barbados', flag: '🇧🇧' },
  { id: 'by', name: 'Belarus', flag: '🇧🇾' },
  { id: 'be', name: 'Belgium', flag: '🇧🇪' },
  { id: 'bz', name: 'Belize', flag: '🇧🇿' },
  { id: 'bj', name: 'Benin', flag: '🇧🇯' },
  { id: 'bt', name: 'Bhutan', flag: '🇧🇹' },
  { id: 'bo', name: 'Bolivia', flag: '🇧🇴' },
  { id: 'ba', name: 'Bosnia and Herzegovina', flag: '🇧🇦' },
  { id: 'bw', name: 'Botswana', flag: '🇧🇼' },
  { id: 'br', name: 'Brazil', flag: '🇧🇷' },
  { id: 'bn', name: 'Brunei', flag: '🇧🇳' },
  { id: 'bg', name: 'Bulgaria', flag: '🇧🇬' },
  { id: 'bf', name: 'Burkina Faso', flag: '🇧🇫' },
  { id: 'bi', name: 'Burundi', flag: '🇧🇮' },
  { id: 'cv', name: 'Cabo Verde', flag: '🇨🇻' },
  { id: 'kh', name: 'Cambodia', flag: '🇰🇭' },
  { id: 'cm', name: 'Cameroon', flag: '🇨🇲' },
  { id: 'ca', name: 'Canada', flag: '🇨🇦' },
  { id: 'cf', name: 'Central African Republic', flag: '🇨🇫' },
  { id: 'td', name: 'Chad', flag: '🇹🇩' },
  { id: 'cl', name: 'Chile', flag: '🇨🇱' },
  { id: 'cn', name: 'China', flag: '🇨🇳' },
  { id: 'co', name: 'Colombia', flag: '🇨🇴' },
  { id: 'km', name: 'Comoros', flag: '🇰🇲' },
  { id: 'cg', name: 'Congo', flag: '🇨🇬' },
  { id: 'cd', name: 'Democratic Republic of the Congo', flag: '🇨🇩' },
  { id: 'cr', name: 'Costa Rica', flag: '🇨🇷' },
  { id: 'hr', name: 'Croatia', flag: '🇭🇷' },
  { id: 'cu', name: 'Cuba', flag: '🇨🇺' },
  { id: 'cy', name: 'Cyprus', flag: '🇨🇾' },
  { id: 'cz', name: 'Czech Republic', flag: '🇨🇿' },
  { id: 'dk', name: 'Denmark', flag: '🇩🇰' },
  { id: 'dj', name: 'Djibouti', flag: '🇩🇯' },
  { id: 'dm', name: 'Dominica', flag: '🇩🇲' },
  { id: 'do', name: 'Dominican Republic', flag: '🇩🇴' },
  { id: 'ec', name: 'Ecuador', flag: '🇪🇨' },
  { id: 'eg', name: 'Egypt', flag: '🇪🇬' },
  { id: 'sv', name: 'El Salvador', flag: '🇸🇻' },
  { id: 'gq', name: 'Equatorial Guinea', flag: '🇬🇶' },
  { id: 'er', name: 'Eritrea', flag: '🇪🇷' },
  { id: 'ee', name: 'Estonia', flag: '🇪🇪' },
  { id: 'sz', name: 'Eswatini', flag: '🇸🇿' },
  { id: 'et', name: 'Ethiopia', flag: '🇪🇹' },
  { id: 'fj', name: 'Fiji', flag: '🇫🇯' },
  { id: 'fi', name: 'Finland', flag: '🇫🇮' },
  { id: 'fr', name: 'France', flag: '🇫🇷' },
  { id: 'ga', name: 'Gabon', flag: '🇬🇦' },
  { id: 'gm', name: 'Gambia', flag: '🇬🇲' },
  { id: 'ge', name: 'Georgia', flag: '🇬🇪' },
  { id: 'de', name: 'Germany', flag: '🇩🇪' },
  { id: 'gh', name: 'Ghana', flag: '🇬🇭' },
  { id: 'gr', name: 'Greece', flag: '🇬🇷' },
  { id: 'gd', name: 'Grenada', flag: '🇬🇩' },
  { id: 'gt', name: 'Guatemala', flag: '🇬🇹' },
  { id: 'gn', name: 'Guinea', flag: '🇬🇳' },
  { id: 'gw', name: 'Guinea-Bissau', flag: '🇬🇼' },
  { id: 'gy', name: 'Guyana', flag: '🇬🇾' },
  { id: 'ht', name: 'Haiti', flag: '🇭🇹' },
  { id: 'hn', name: 'Honduras', flag: '🇭🇳' },
  { id: 'hu', name: 'Hungary', flag: '🇭🇺' },
  { id: 'is', name: 'Iceland', flag: '🇮🇸' },
  { id: 'in', name: 'India', flag: '🇮🇳' },
  { id: 'id', name: 'Indonesia', flag: '🇮🇩' },
  { id: 'ir', name: 'Iran', flag: '🇮🇷' },
  { id: 'iq', name: 'Iraq', flag: '🇮🇶' },
  { id: 'ie', name: 'Ireland', flag: '🇮🇪' },
  { id: 'il', name: 'Israel', flag: '🇮🇱' },
  { id: 'it', name: 'Italy', flag: '🇮🇹' },
  { id: 'ci', name: 'Ivory Coast', flag: '🇨🇮' },
  { id: 'jm', name: 'Jamaica', flag: '🇯🇲' },
  { id: 'jp', name: 'Japan', flag: '🇯🇵' },
  { id: 'jo', name: 'Jordan', flag: '🇯🇴' },
  { id: 'kz', name: 'Kazakhstan', flag: '🇰🇿' },
  { id: 'ke', name: 'Kenya', flag: '🇰🇪' },
  { id: 'ki', name: 'Kiribati', flag: '🇰🇮' },
  { id: 'kp', name: 'North Korea', flag: '🇰🇵' },
  { id: 'kr', name: 'South Korea', flag: '🇰🇷' },
  { id: 'kw', name: 'Kuwait', flag: '🇰🇼' },
  { id: 'kg', name: 'Kyrgyzstan', flag: '🇰🇬' },
  { id: 'la', name: 'Laos', flag: '🇱🇦' },
  { id: 'lv', name: 'Latvia', flag: '🇱🇻' },
  { id: 'lb', name: 'Lebanon', flag: '🇱🇧' },
  { id: 'ls', name: 'Lesotho', flag: '🇱🇸' },
  { id: 'lr', name: 'Liberia', flag: '🇱🇷' },
  { id: 'ly', name: 'Libya', flag: '🇱🇾' },
  { id: 'li', name: 'Liechtenstein', flag: '🇱🇮' },
  { id: 'lt', name: 'Lithuania', flag: '🇱🇹' },
  { id: 'lu', name: 'Luxembourg', flag: '🇱🇺' },
  { id: 'mg', name: 'Madagascar', flag: '🇲🇬' },
  { id: 'mw', name: 'Malawi', flag: '🇲🇼' },
  { id: 'my', name: 'Malaysia', flag: '🇲🇾' },
  { id: 'mv', name: 'Maldives', flag: '🇲🇻' },
  { id: 'ml', name: 'Mali', flag: '🇲🇱' },
  { id: 'mt', name: 'Malta', flag: '🇲🇹' },
  { id: 'mh', name: 'Marshall Islands', flag: '🇲🇭' },
  { id: 'mr', name: 'Mauritania', flag: '🇲🇷' },
  { id: 'mu', name: 'Mauritius', flag: '🇲🇺' },
  { id: 'mx', name: 'Mexico', flag: '🇲🇽' },
  { id: 'fm', name: 'Micronesia', flag: '🇫🇲' },
  { id: 'md', name: 'Moldova', flag: '🇲🇩' },
  { id: 'mc', name: 'Monaco', flag: '🇲🇨' },
  { id: 'mn', name: 'Mongolia', flag: '🇲🇳' },
  { id: 'me', name: 'Montenegro', flag: '🇲🇪' },
  { id: 'ma', name: 'Morocco', flag: '🇲🇦' },
  { id: 'mz', name: 'Mozambique', flag: '🇲🇿' },
  { id: 'mm', name: 'Myanmar', flag: '🇲🇲' },
  { id: 'na', name: 'Namibia', flag: '🇳🇦' },
  { id: 'nr', name: 'Nauru', flag: '🇳🇷' },
  { id: 'np', name: 'Nepal', flag: '🇳🇵' },
  { id: 'nl', name: 'Netherlands', flag: '🇳🇱' },
  { id: 'nz', name: 'New Zealand', flag: '🇳🇿' },
  { id: 'ni', name: 'Nicaragua', flag: '🇳🇮' },
  { id: 'ne', name: 'Niger', flag: '🇳🇪' },
  { id: 'ng', name: 'Nigeria', flag: '🇳🇬' },
  { id: 'mk', name: 'North Macedonia', flag: '🇲🇰' },
  { id: 'no', name: 'Norway', flag: '🇳🇴' },
  { id: 'om', name: 'Oman', flag: '🇴🇲' },
  { id: 'pk', name: 'Pakistan', flag: '🇵🇰' },
  { id: 'pw', name: 'Palau', flag: '🇵🇼' },
  { id: 'ps', name: 'Palestine', flag: '🇵🇸' },
  { id: 'pa', name: 'Panama', flag: '🇵🇦' },
  { id: 'pg', name: 'Papua New Guinea', flag: '🇵🇬' },
  { id: 'py', name: 'Paraguay', flag: '🇵🇾' },
  { id: 'pe', name: 'Peru', flag: '🇵🇪' },
  { id: 'ph', name: 'Philippines', flag: '🇵🇭' },
  { id: 'pl', name: 'Poland', flag: '🇵🇱' },
  { id: 'pt', name: 'Portugal', flag: '🇵🇹' },
  { id: 'qa', name: 'Qatar', flag: '🇶🇦' },
  { id: 'ro', name: 'Romania', flag: '🇷🇴' },
  { id: 'ru', name: 'Russia', flag: '🇷🇺' },
  { id: 'rw', name: 'Rwanda', flag: '🇷🇼' },
  { id: 'kn', name: 'Saint Kitts and Nevis', flag: '🇰🇳' },
  { id: 'lc', name: 'Saint Lucia', flag: '🇱🇨' },
  { id: 'vc', name: 'Saint Vincent and the Grenadines', flag: '🇻🇨' },
  { id: 'ws', name: 'Samoa', flag: '🇼🇸' },
  { id: 'sm', name: 'San Marino', flag: '🇸🇲' },
  { id: 'st', name: 'Sao Tome and Principe', flag: '🇸🇹' },
  { id: 'sa', name: 'Saudi Arabia', flag: '🇸🇦' },
  { id: 'sn', name: 'Senegal', flag: '🇸🇳' },
  { id: 'rs', name: 'Serbia', flag: '🇷🇸' },
  { id: 'sc', name: 'Seychelles', flag: '🇸🇨' },
  { id: 'sl', name: 'Sierra Leone', flag: '🇸🇱' },
  { id: 'sg', name: 'Singapore', flag: '🇸🇬' },
  { id: 'sk', name: 'Slovakia', flag: '🇸🇰' },
  { id: 'si', name: 'Slovenia', flag: '🇸🇮' },
  { id: 'sb', name: 'Solomon Islands', flag: '🇸🇧' },
  { id: 'so', name: 'Somalia', flag: '🇸🇴' },
  { id: 'za', name: 'South Africa', flag: '🇿🇦' },
  { id: 'ss', name: 'South Sudan', flag: '🇸🇸' },
  { id: 'es', name: 'Spain', flag: '🇪🇸' },
  { id: 'lk', name: 'Sri Lanka', flag: '🇱🇰' },
  { id: 'sd', name: 'Sudan', flag: '🇸🇩' },
  { id: 'sr', name: 'Suriname', flag: '🇸🇷' },
  { id: 'se', name: 'Sweden', flag: '🇸🇪' },
  { id: 'ch', name: 'Switzerland', flag: '🇨🇭' },
  { id: 'sy', name: 'Syria', flag: '🇸🇾' },
  { id: 'tw', name: 'Taiwan', flag: '🇹🇼' },
  { id: 'tj', name: 'Tajikistan', flag: '🇹🇯' },
  { id: 'tz', name: 'Tanzania', flag: '🇹🇿' },
  { id: 'th', name: 'Thailand', flag: '🇹🇭' },
  { id: 'tl', name: 'Timor-Leste', flag: '🇹🇱' },
  { id: 'tg', name: 'Togo', flag: '🇹🇬' },
  { id: 'to', name: 'Tonga', flag: '🇹🇴' },
  { id: 'tt', name: 'Trinidad and Tobago', flag: '🇹🇹' },
  { id: 'tn', name: 'Tunisia', flag: '🇹🇳' },
  { id: 'tr', name: 'Turkey', flag: '🇹🇷' },
  { id: 'tm', name: 'Turkmenistan', flag: '🇹🇲' },
  { id: 'tv', name: 'Tuvalu', flag: '🇹🇻' },
  { id: 'ug', name: 'Uganda', flag: '🇺🇬' },
  { id: 'ua', name: 'Ukraine', flag: '🇺🇦' },
  { id: 'ae', name: 'United Arab Emirates', flag: '🇦🇪' },
  { id: 'uk', name: 'United Kingdom', flag: '🇬🇧' },
  { id: 'us', name: 'United States', flag: '🇺🇸' },
  { id: 'uy', name: 'Uruguay', flag: '🇺🇾' },
  { id: 'uz', name: 'Uzbekistan', flag: '🇺🇿' },
  { id: 'vu', name: 'Vanuatu', flag: '🇻🇺' },
  { id: 'va', name: 'Vatican City', flag: '🇻🇦' },
  { id: 've', name: 'Venezuela', flag: '🇻🇪' },
  { id: 'vn', name: 'Vietnam', flag: '🇻🇳' },
  { id: 'ye', name: 'Yemen', flag: '🇾🇪' },
  { id: 'zm', name: 'Zambia', flag: '🇿🇲' },
  { id: 'zw', name: 'Zimbabwe', flag: '🇿🇼' },
];

export const ACADEMIC_EXAMS_BY_COUNTRY: Record<string, string[]> = {
  global: ['IB Diploma', 'IGCSE', 'IELTS', 'TOEFL', 'SAT', 'ACT'],
  af: ['Kankor Exam', 'Primary School Final Exam', 'Grade 9 National Exam'],
  al: ['Matura Shtetërore (State Matura)', 'Provimet e Lirimit (Grade 9 Exam)'],
  dz: ['Baccalauréat (BAC)', 'Brevet d\'Enseignement Moyen (BEM)'],
  ad: ['Prova Oficial de Batxillerat (POB)', 'Selectivitat (EBAU - Spain)', 'Baccalauréat (France)'],
  ao: ['Exames Nacionais de Diagnóstico', 'Exame de Admissão Ensino Superior'],
  ag: ['CSEC (CXC)', 'CAPE (CXC)', 'CPEA'],
  ar: ['Pruebas Aprender', 'CBC (Ciclo Básico Común - UBA)'],
  am: ['Unified Entrance Examinations (State Exit Exams)'],
  au: ['HSC (NSW)', 'VCE (Victoria)', 'QCE (Queensland)', 'WACE (WA)', 'SACE (SA)', 'ATAR / STAT'],
  at: ['Reifeprüfung / Matura', 'MedAT (Medical Admissions)', 'Fachhochschul-Aufnahmeprüfung'],
  az: ['State Examination Center (SEC) Entrance Exams', 'Grade 9/11 Graduation Exams'],
  bs: ['BGCSE', 'BJC (Bahamas Junior Certificate)'],
  bh: ['General Secondary Education Certificate (Tawjihi)'],
  bd: ['PSC', 'JSC', 'SSC', 'HSC', 'Medical Admission Test (MAT)', 'BUET Admission Test'],
  bb: ['CSEC (CXC)', 'CAPE (CXC)', 'BSSEE (11-Plus)'],
  by: ['Centralized Testing (CT)', 'Centralized Exam (CE)'],
  be: ['CEB (Certificat d\'Études de Base)', 'CE1D', 'CESS', 'Examen d\'Admission aux Études Médicales'],
  bz: ['PSE (Primary School Examination)', 'CSEC (CXC)', 'ATLIB Tertiary Exams'],
  bj: ['BAC (Baccalauréat)', 'BEPC', 'CEP'],
  bt: ['BCSE (Class 10)', 'BHSEC (Class 12)', 'BCSE (Civil Service Examination)'],
  bo: ['Pruebas Saber / Evaluación del Sistema Educativo', 'Exámenes de Admisión Universitaria'],
  ba: ['Matura', 'Extema Matura'],
  bw: ['PSLE', 'JCE', 'BGCSE'],
  br: ['ENEM', 'Fuvest (USP)', 'Unicamp', 'PAS / Vestibular'],
  bn: ['PSR (Primary 6)', 'SPE (Form 2)', 'GCE O-Level', 'GCE A-Level'],
  bg: ['National External Assessment (NVO Grade 4/7/10)', 'State Matriculation Exams (Matura)'],
  bf: ['CEP', 'BEPC', 'Baccalauréat (BAC)'],
  bi: ['Concours National de 9ème', 'Examen d\'État (Diplôme d\'État)'],
  cv: ['Provas Aferidoras', 'Exames Nacionais do Ensino Secundário'],
  kh: ['Grade 9 National Exam', 'Bac II (Baccalauréat / Upper Secondary Exam)'],
  cm: ['GCE O-Level (Anglophone)', 'GCE A-Level (Anglophone)', 'BEPC (Francophone)', 'Baccalauréat (Francophone)'],
  ca: ['Provincial Assessment Exams (e.g., BC Provincial, Ontario Literacy Test - OSSLT)', 'CASPer', 'MCAT Canada'],
  cf: ['DEF (Diplôme d\'Études Fondamentales)', 'Baccalauréat (BAC)'],
  td: ['BEPC', 'Baccalauréat (BAC)'],
  cl: ['PAES (Prueba de Acceso a la Educación Superior)', 'SIMCE'],
  cn: ['Gaokao (National College Entrance Examination)', 'Zhongkao (Senior High School Entrance)'],
  co: ['Saber 3, 5, 9', 'Saber 11 (ICFES)', 'Saber Pro'],
  km: ['6ème Exam', 'Brevet', 'Baccalauréat (BAC)'],
  cg: ['CEPE', 'BEPC', 'Baccalauréat (BAC)'],
  cd: ['TENAFEP', 'TENASOSP', 'Examen d\'État (EXAETAT)'],
  cr: ['Pruebas Nacionales FARO', 'Examen de Admisión UCR / TEC / UNA'],
  hr: ['Državna Matura (State Matura)'],
  cu: ['Pruebas de Ingreso a la Educación Superior (Ingreso a la Universidad)'],
  cy: ['Pancyprian Examinations (Pankypries Exetaseis)'],
  cz: ['Maturita (Maturitní zkouška)', 'Jednotná přijímací zkouška (Cermat)'],
  dk: ['Folkeskolens Afgangsprøve (9th Grade)', 'STX / HHX / HTX / HF Upper Secondary Exams'],
  dj: ['CEPE', 'BEPC', 'Baccalauréat (BAC)'],
  dm: ['GACE (Grade 6)', 'CSEC (CXC)', 'CAPE (CXC)'],
  do: ['Pruebas Nacionales (Grade 6, 9, 12)', 'POMA / PAA (University Placement)'],
  ec: ['Evaluación Transformar / Examen de Acceso a la Educación Superior', 'Pruebas Aprender / Ser Bachiller'],
  eg: ['Thanaweya Amma (Secondary Education Certificate)', 'STEM High School Admissions'],
  sv: ['PAES / Prueba AVANZO'],
  gq: ['Selectividad / Examen de Madurez Nacional'],
  er: ['Eritrean Secondary Education Certificate Examination (EAC / ESECE)'],
  ee: ['Põhikooli lõpueksamid (Grade 9)', 'Riigieksamid (State High School Exams)'],
  sz: ['EPC', 'JC', 'EGCSE (Eswatini General Certificate of Secondary Education)'],
  et: ['Grade 8 Regional Exam', 'EGSECE (Grade 10)', 'EESALE (Grade 12 University Entrance)'],
  fj: ['Fiji Year 8 Examination (FY8E)', 'Fiji Year 12 Certificate', 'Fiji Year 13 Certificate'],
  fi: ['Ylioppilastutkinto (Matriculation Examination)'],
  fr: ['Diplôme National du Brevet (DNB)', 'Baccalauréat (General, Technologique, Professionnel)'],
  ga: ['CEPE', 'BEPC', 'Baccalauréat (BAC)'],
  gm: ['GABECE', 'WASSCE (WAEC)'],
  ge: ['Unified National Examinations (NAEC)'],
  de: ['Abitur (Allgemeine Hochschulreife)', 'MSA (Mittlerer Schulabschluss)', 'Hauptschulabschluss'],
  gh: ['BECE', 'WASSCE (WAEC)'],
  gr: ['Panhellenic Examinations (Panelladikes Exetaseis)'],
  gd: ['CPEA', 'CSEC (CXC)', 'CAPE (CXC)'],
  gt: ['Evaluación de Graduandos (MINEDUC)', 'Exámenes de Admisión USAC'],
  gn: ['CEE (Certificat d\'Études Élémentaires)', 'BEPC', 'Baccalauréat (BAC Single)'],
  gw: ['Exames Nacionais do Ensino Básico e Secundário'],
  gy: ['NGSA (National Grade Six Assessment)', 'CSEC (CXC)', 'CAPE (CXC)'],
  ht: ['Examen de 9ème Année Fondamentale', 'Baccalauréat Permanent / Unique'],
  hn: ['Prueba de Aptitud Académica (PAA - UNAH)'],
  hu: ['Matura (Érettségi vizsga)'],
  is: ['Samræmd próf (Standardized National Exams)', 'Stúdentspróf (Matriculation)'],
  in: ['CBSE Class 10/12', 'ICSE / ISC', 'JEE Main & Advanced', 'NEET UG', 'UPSC CSE', 'GATE'],
  id: ['Ujian Sekolah (US)', 'UTBK-SNBT (University Entrance)', 'SNBP'],
  ir: ['Konkur (National University Entrance Exam)', 'Final High School Exams (Imtehanat-e Nahaei)'],
  iq: ['Baccalaureate Exams (Grade 6 Primary, Grade 9 Middle, Grade 12 Secondary)'],
  ie: ['Junior Cycle Certificate', 'Leaving Certificate (Leaving Cert)'],
  il: ['Bagrut (Matriculation Exams)', 'Psychometric Entrance Test (PET)'],
  it: ['Esame di Terza Media', 'Esame di Stato (Maturità)', 'TOLC (University Entrance Tests)'],
  ci: ['CEPE', 'BEPC', 'Baccalauréat (BAC)'],
  jm: ['PEP (Primary Exit Profile)', 'CSEC (CXC)', 'CAPE (CXC)'],
  jp: ['Common Test for University Admissions (Kyotsu Test)', 'High School Entrance Exams'],
  jo: ['Tawjihi (General Secondary Education Certificate Examination)'],
  kz: ['UNT (Unified National Testing / UBTT)'],
  ke: ['KPSEA', 'KCPE (Legacy)', 'KCSE (Kenya Certificate of Secondary Education)'],
  ki: ['Kiribati National Certificate of Education (K N C E)'],
  kp: ['State Graduation Examination / University Entrance Examination'],
  kr: ['CSAT / Suneung (College Scholastic Ability Test)'],
  kw: ['General Secondary School Certificate (Shahadat Al-Thanawiya Al-Amma)'],
  kg: ['ORT (National Scholarship Testing / Nationwide Testing)'],
  la: ['Lower Secondary Exit Exam (Grade 9)', 'Upper Secondary National Exam (Grade 12)'],
  lv: ['Centralizētie eksāmeni (Centralized Exams - Grade 9 & 12)'],
  lb: ['Brevet (Official Middle School Exam)', 'Baccalauréat Libanais (Official Secondary Exam)'],
  ls: ['LPSLE', 'JC Exam', 'LGCSE'],
  lr: ['LJHSCE', 'WASCE / WASSCE (WAEC)'],
  ly: ['Basic Education Certificate (Grade 9)', 'Secondary Education Certificate (Grade 12)'],
  li: ['Matura (Gymnasiale Maturität - Switzerland model)'],
  lt: ['Valstybiniai brandos egzaminai (VBE - State Maturity Exams)'],
  lu: ['Examen de Fin d\'Études Secondaires'],
  mg: ['CEPE', 'BEPC', 'Baccalauréat (BAC)'],
  mw: ['PSLCE', 'JCE', 'MSCE (Malawi School Certificate of Education)'],
  my: ['SPM (Sijil Pelajaran Malaysia)', 'STPM (Sijil Tinggi Persekolahan Malaysia)', 'UPPU'],
  mv: ['O-Level (IGCSE)', 'A-Level (GCE)', 'HSC (Higher Secondary Certificate)'],
  ml: ['DEF', 'Diplôme du Baccalauréat (BAC)'],
  mt: ['SEC (O-Levels / MATSEC)', 'Matriculation Certificate (Advanced & Intermediate Level)'],
  mh: ['MISAT (Marshall Islands Standardized Achievement Test)'],
  mr: ['Brevet (BEPC)', 'Baccalauréat (BAC)'],
  mu: ['PSAC (Primary School Achievement Certificate)', 'NCFE', 'SC (School Certificate / O-Level)', 'HSC (A-Level)'],
  mx: ['EXANI-I', 'EXANI-II (CENEVAL)', 'UNAM / IPN Entrance Exams'],
  fm: ['COM-FSM Entrance Test (COMET)', 'NST (National Standardized Tests)'],
  md: ['Examenul Național de Capacitate (Grade 9)', 'Examenul Național de Bacalaureat'],
  mc: ['Brevet des Collèges', 'Baccalauréat (French System)'],
  mn: ['General Entrance Exam (EYE / EEE)'],
  me: ['Mala Matura (Grade 9)', 'Maturski Ispit (State Matura)'],
  ma: ['Examens Régionaux (1st Bac)', 'Examen National du Baccalauréat'],
  mz: ['Exames Nacionales de 10ª Classe', 'Exames Nacionales de 12ª Classe', 'Exames de Admissão à Universidade'],
  mm: ['Basic Education High School Examination (Matriculation Examination)'],
  na: ['NSSCO (Namibia Senior Secondary Certificate Ordinary)', 'NSSCAS (Advanced Subsidiary)'],
  nr: ['CAPS / Pacific Senior Secondary Certificate (PSSC)'],
  np: ['SEE (Secondary Education Examination - Grade 10)', 'Class 12 National Board Exam (NEB)', 'IOE / IOM Entrance'],
  nl: ['Central Exams (Eindexamen - VMBO, HAVO, VWO)'],
  nz: ['NCEA Level 1', 'NCEA Level 2', 'NCEA Level 3 / NZ Scholarship'],
  ni: ['Examen de Admisión UNI / UNAN'],
  ne: ['CFEPD', 'BEPC', 'Baccalauréat (BAC)'],
  ng: ['WAEC (WASSCE)', 'NECO', 'JAMB (UTME)', 'Post-UTME', 'NABTEB', 'BECE'],
  mk: ['Državna Matura (State Matura)'],
  no: ['Eksamen i Videregående Opplæring (High School Exams)', 'Nasjonale Prøver'],
  om: ['General Education Diploma (General Secondary Certificate)'],
  pk: ['Matriculation (SSC - Class 9/10)', 'Intermediate (HSSC - Class 11/12)', 'MDCAT', 'ECAT'],
  pw: ['PPEC (Palau High School Entrance Exam)', 'PTEC'],
  ps: ['Tawjihi (Injaz - General Secondary Education Certificate)'],
  pa: ['Exámenes de Admisión UP / UTP'],
  pg: ['Grade 8 National Exam', 'Grade 10 National Exam', 'Grade 12 Upper Secondary Exam (USSCE)'],
  py: ['Pruebas Saber / Examen de Egreso Educación Media'],
  pe: ['Pruebas ECE / Muestral', 'Examen de Admisión UNI / UNMSM / PUCP'],
  ph: ['NAT (National Achievement Test)', 'NMAT', 'UPCAT', 'PUPCET', 'USTET'],
  pl: ['Egzamin Ósmoklasisty (8th Grade Exam)', 'Egzamin Maturalny (Matura)'],
  pt: ['Provas Finais do Básico', 'Exames Nacionais do Ensino Secundário'],
  qa: ['General Secondary Education Certificate (Thanaweya Amma)'],
  ro: ['Evaluarea Națională (Grade 8)', 'Examenul Național de Bacalaureat'],
  ru: ['OGE (Basic State Exam - Grade 9)', 'EGE (Unified State Exam - Grade 11)'],
  rw: ['P6 Primary Leaving Exam (PLE)', 'S3 Ordinary Level Exam (O-Level)', 'S6 Advanced Level Exam (A-Level)'],
  kn: ['CSEC (CXC)', 'CAPE (CXC)'],
  lc: ['CPEA', 'CSEC (CXC)', 'CAPE (CXC)'],
  vc: ['CPEA', 'CSEC (CXC)', 'CAPE (CXC)'],
  ws: ['SPECA (Year 8)', 'SAME (Year 12)', 'SSLC (Year 13 / Samoa Secondary Leaving Certificate)'],
  sm: ['Esame di Stato (San Marino / Italian curriculum)'],
  st: ['Exames Nacionais do Ensino Secundário'],
  sa: ['Qiyas - Qudrat (General Aptitude Test)', 'Qiyas - Tahsili (Scholastic Achievement Test)'],
  sn: ['CFEE', 'BFEM', 'Baccalauréat (BAC)'],
  rs: ['Mala Matura (Grade 8 Final Exam)', 'Velika Matura (State Matura)'],
  sc: ['National Examinations (Grade 6 & 9)', 'IGCSE', 'A-Levels'],
  sl: ['NPSE', 'BECE', 'WASSCE (WAEC)'],
  sg: ['PSLE', 'GCE N-Level', 'GCE O-Level', 'GCE A-Level'],
  sk: ['Maturita (Maturitná skúška)', 'Testovanie 9 (Monitor 9)'],
  si: ['Poklicna Matura', 'Splošna Matura (General Matura)', 'NPZ (Grade 6/9)'],
  sb: ['SINTA (Form 3)', 'PSSC / SISC (Form 5)', 'SPFSC (Form 6)'],
  so: ['National Middle School Exam (Grade 8)', 'National Secondary School Leaving Exam (Grade 12)'],
  za: ['NSC (National Senior Certificate / Matric)', 'IEB Exams', 'NBT (National Benchmark Tests)'],
  ss: ['PLE (Primary Leaving Examination)', 'CSE (Certificate of Secondary Education)'],
  es: ['Selectividad / EBAU / EvAU (PAU)', 'Pruebas de Diagnostic (ESO)'],
  lk: ['GCE O-Level', 'GCE A-Level', 'Scholarship Exam (Grade 5)'],
  sd: ['Basic Education Certificate Exam', 'Sudanese Secondary School Certificate (Sudan Baccalaureate)'],
  sr: ['GLO-toets', 'MULO-examen', 'VWO / HAVO eindexamen'],
  se: ['Nationella prov (National Standardized Tests)', 'Högskoleprovet (Swedish Scholastic Aptitude Test)'],
  ch: ['Schweizerische Maturitätsprüfung (Maturité / Maturità)'],
  sy: ['Shahadat Al-Ta\'leem Al-Asasi (9th Grade)', 'Al-Thanaweya Al-Amma (Baccalaureate)'],
  tw: ['CAP (Comprehensive Assessment Program - Junior High)', 'GSAT (General Scholastic Ability Test)', 'AST (Advanced Subjects Test)'],
  tj: ['National Testing Center Exams (NTC Entrance Exams)'],
  tz: ['PSLE (Standard 7)', 'FTNA (Form 2)', 'CSEE (Form 4)', 'ACSEE (Form 6)'],
  th: ['O-NET (Ordinary National Educational Test)', 'TCAS (A-Level / TPAT / TGAT)'],
  tl: ['Exame Nacional do 9º Ano', 'Exame Nacional do 12º Ano'],
  tg: ['CEPD', 'BEPC', 'Baccalauréat (BAC 1 & BAC 2)'],
  to: ['Tonga School Certificate (Form 5)', 'Pacific Senior Secondary Certificate (PSSC - Form 6)'],
  tt: ['SEA (Secondary Entrance Assessment)', 'CSEC (CXC)', 'CAPE (CXC)'],
  tn: ['Diplôme de Fin d\'Études de l\'Enseignement de Base', 'Baccalauréat Tunisien (BAC)'],
  tr: ['LGS (High School Entrance)', 'YKS (TYT / AYT / YDT - University Entrance)'],
  tm: ['State Secondary School Certificate / Higher Education Entrance Examinations'],
  tv: ['Tuvalu Junior Certificate (TJC)', 'PSSC (Pacific Senior Secondary Certificate)'],
  ug: ['PLE (Primary Leaving Examination)', 'UCE (Uganda Certificate of Education)', 'UACE (Uganda Advanced Certificate of Education)'],
  ua: ['NMT (National Multi-subject Test)', 'ZNO (External Independent Evaluation)'],
  ae: ['EmSAT (Emirates Standardized Test)', 'Grade 12 Ministry Exams'],
  uk: ['GCSE', 'A-Levels', 'T-Levels', 'Scottish Highers / Advanced Highers', 'IB Diploma', 'UCAT'],
  us: ['SAT', 'ACT', 'AP Exams', 'GRE', 'GMAT', 'MCAT', 'LSAT'],
  uy: ['Pruebas Aristas', 'Exámenes de Enseñanza Secundaria (CES)'],
  uz: ['DTM (State Testing Center Entrance Exams)'],
  vu: ['Year 8 Exam', 'Year 10 Exam', 'VSSC (Year 12)', 'SPFSC (Year 13)'],
  va: ['Pontifical Academy Assessment / Italian National Standardized Tests'],
  ve: ['Prueba de Aptitud Académica (OPSU)'],
  vn: ['Grade 10 High School Entrance Exam', 'National High School Graduation Exam (Kỳ thi Tốt nghiệp THPT)'],
  ye: ['Basic Education Certificate (Grade 9)', 'General Secondary Education Certificate (Grade 12 / Al-Thanaweya)'],
  zm: ['Grade 7 Composite Exam', 'Grade 9 External Exam', 'ECZ Grade 12 Senior Secondary Examination'],
  zw: ['ZIMSEC Grade 7', 'ZIMSEC O-Level', 'ZIMSEC A-Level'],
};

export const PROFESSIONAL_DOMAINS: ProfessionalDomain[] = [
  { id: 'cloud', label: 'Cloud Computing', icon: '☁️', examples: ['AWS Solutions Architect', 'Azure Administrator', 'GCP Architect'] },
  { id: 'cyber', label: 'Cybersecurity', icon: '🛡️', examples: ['CompTIA Security+', 'CEH', 'CISSP', 'CISM'] },
  { id: 'dev', label: 'Software & DevOps', icon: '💻', examples: ['CKA', 'Docker Certified', 'Meta Frontend'] },
  { id: 'data', label: 'Data & AI', icon: '📊', examples: ['TensorFlow Developer', 'AWS Data Analytics', 'Databricks'] },
  { id: 'finance', label: 'Finance & Accounting', icon: '📈', examples: ['CFA', 'CPA', 'ACCA', 'FRM'] },
  { id: 'mgmt', label: 'Management', icon: '📋', examples: ['PMP', 'CAPM', 'PSM I', 'PRINCE2'] },
  { id: 'medical', label: 'Healthcare & Medicine', icon: '🩺', examples: ['NCLEX-RN', 'USMLE Step 1/2', 'PLAB'] },
  { id: 'other', label: 'Other Industry Domain', icon: '🌐', examples: [''] },
];


export const COMMON_SUBJECTS: Record<string, string[]> = {
  Sciences: [
    'Mathematics',
    'Further Mathematics / Pure Math',
    'Physics',
    'Chemistry',
    'Biology',
    'Biotechnology',
    'Environmental Science',
    'Earth & Space Science',
    'Astronomy',
    'Geology',
    'Computer Science',
    'Computer Studies / ICT',
    'Data Science / Statistics',
    'Information Technology',
    'Engineering Drawing / Graphics',
    'Health Science / Anatomy',
    'Psychology',
    'Agricultural Science',
    'Food & Nutrition',
    'Physical Education',
    'Sports Science',
  ],
  Commercial: [
    'Economics',
    'Commerce',
    'Finance',
    'Accounting',
    'Business Studies',
    'Business Management',
    'Entrepreneurship',
    'Marketing',
    'Statistics',
    'Financial Accounting',
    'Cost Accounting',
    'Auditing',
    'Bookkeeping',
    'Office Practice',
    'Business Mathematics',
    'Business Statistics',
    'Insurance',
    'Store Management',
    'Banking & Finance',
    'Salesmanship',
  ],
  Arts: [
    'English Language',
    'Literature in English',
    'Government',
    'Political Science',
    'Philosophy',
    'Fine Arts',
    'Physical Education',
    'Legal Studies',
    'Journalism',
    'Home Science',
    'History',
    'World History',
    'Geography',
    'Civic Education',
    'Sociology',
    'Logic & Ethics',
    'Anthropology',
    'Visual Arts',
    'Music',
    'Theatre Arts',
    'Media Studies',
    'Home Management',
    'Design & Textiles',
  ],
  General: [
    'General Knowledge',
    'Critical Reasoning',
    'Quantitative Reasoning',
    'Reasoning / Aptitude',
    'Logical & Analytical Reasoning',
    'Reading Comprehension',
    'Data Interpretation',
    'Numerical Ability',
    'Abstract Reasoning',
    'General Science Awareness',
    'Digital Literacy',
  ],
};