export interface LanguageOption {
  code: string;
  name: string;      // English name
  nativeName: string; // Native name
  script: string;
}

export const LANGUAGES: LanguageOption[] = [
  { code: 'af', name: 'Afrikaans', nativeName: 'Afrikaans', script: 'Latin' },
  { code: 'sq', name: 'Albanian', nativeName: 'Shqip', script: 'Latin' },
  { code: 'am', name: 'Amharic', nativeName: 'አማርኛ', script: 'Ge\'ez' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', script: 'Arabic' },
  { code: 'hy', name: 'Armenian', nativeName: 'Հայերեն', script: 'Armenian' },
  { code: 'az', name: 'Azerbaijani', nativeName: 'Azərbaycan dili', script: 'Latin' },
  { code: 'eu', name: 'Basque', nativeName: 'Euskara', script: 'Latin' },
  { code: 'be', name: 'Belarusian', nativeName: 'Беларуская', script: 'Cyrillic' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', script: 'Bengali' },
  { code: 'bs', name: 'Bosnian', nativeName: 'Bosanski', script: 'Latin' },
  { code: 'bg', name: 'Bulgarian', nativeName: 'Български', script: 'Cyrillic' },
  { code: 'my', name: 'Burmese', nativeName: 'ဗမာစာ', script: 'Myanmar' },
  { code: 'ca', name: 'Catalan', nativeName: 'Català', script: 'Latin' },
  { code: 'zh', name: 'Chinese (Simplified)', nativeName: '简体中文', script: 'Hanzi' },
  { code: 'zh-TW', name: 'Chinese (Traditional)', nativeName: '繁體中文', script: 'Hanzi' },
  { code: 'hr', name: 'Croatian', nativeName: 'Hrvatski', script: 'Latin' },
  { code: 'cs', name: 'Czech', nativeName: 'Čeština', script: 'Latin' },
  { code: 'da', name: 'Danish', nativeName: 'Dansk', script: 'Latin' },
  { code: 'nl', name: 'Dutch', nativeName: 'Nederlands', script: 'Latin' },
  { code: 'en', name: 'English', nativeName: 'English', script: 'Latin' },
  { code: 'eo', name: 'Esperanto', nativeName: 'Esperanto', script: 'Latin' },
  { code: 'et', name: 'Estonian', nativeName: 'Eesti', script: 'Latin' },
  { code: 'fi', name: 'Finnish', nativeName: 'Suomi', script: 'Latin' },
  { code: 'fr', name: 'French', nativeName: 'Français', script: 'Latin' },
  { code: 'gl', name: 'Galician', nativeName: 'Galego', script: 'Latin' },
  { code: 'ka', name: 'Georgian', nativeName: 'ქართული', script: 'Georgian' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', script: 'Latin' },
  { code: 'el', name: 'Greek', nativeName: 'Ελληνικά', script: 'Greek' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', script: 'Gujarati' },
  { code: 'ht', name: 'Haitian Creole', nativeName: 'Kreyòl ayisyen', script: 'Latin' },
  { code: 'ha', name: 'Hausa', nativeName: 'Hausa', script: 'Latin' },
  { code: 'he', name: 'Hebrew', nativeName: 'עברית', script: 'Hebrew' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', script: 'Devanagari' },
  { code: 'hu', name: 'Hungarian', nativeName: 'Magyar', script: 'Latin' },
  { code: 'is', name: 'Icelandic', nativeName: 'Íslenska', script: 'Latin' },
  { code: 'ig', name: 'Igbo', nativeName: 'Asụsụ Igbo', script: 'Latin' },
  { code: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia', script: 'Latin' },
  { code: 'ga', name: 'Irish', nativeName: 'Gaeilge', script: 'Latin' },
  { code: 'it', name: 'Italian', nativeName: 'Italiano', script: 'Latin' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', script: 'Kanji/Kana' },
  { code: 'jv', name: 'Javanese', nativeName: 'Basa Jawa', script: 'Latin' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', script: 'Kannada' },
  { code: 'kk', name: 'Kazakh', nativeName: 'Қазақ тілі', script: 'Cyrillic' },
  { code: 'km', name: 'Khmer', nativeName: 'ភាសាខ្មែរ', script: 'Khmer' },
  { code: 'rw', name: 'Kinyarwanda', nativeName: 'Ikinyarwanda', script: 'Latin' },
  { code: 'ko', name: 'Korean', nativeName: '한국어', script: 'Hangul' },
  { code: 'ku', name: 'Kurdish', nativeName: 'Kurdî', script: 'Latin' },
  { code: 'ky', name: 'Kyrgyz', nativeName: 'Кыргызча', script: 'Cyrillic' },
  { code: 'lo', name: 'Lao', nativeName: 'ພາສາລາວ', script: 'Lao' },
  { code: 'la', name: 'Latin', nativeName: 'Lingua Latina', script: 'Latin' },
  { code: 'lv', name: 'Latvian', nativeName: 'Latviešu', script: 'Latin' },
  { code: 'lt', name: 'Lithuanian', nativeName: 'Lietuvių', script: 'Latin' },
  { code: 'lb', name: 'Luxembourgish', nativeName: 'Lëtzebuergesch', script: 'Latin' },
  { code: 'mk', name: 'Macedonian', nativeName: 'Македонски', script: 'Cyrillic' },
  { code: 'mg', name: 'Malagasy', nativeName: 'Malagasy', script: 'Latin' },
  { code: 'ms', name: 'Malay', nativeName: 'Bahasa Melayu', script: 'Latin' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', script: 'Malayalam' },
  { code: 'mt', name: 'Maltese', nativeName: 'Malti', script: 'Latin' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', script: 'Devanagari' },
  { code: 'mn', name: 'Mongolian', nativeName: 'Монгол хэл', script: 'Cyrillic' },
  { code: 'ne', name: 'Nepali', nativeName: 'नेपाली', script: 'Devanagari' },
  { code: 'no', name: 'Norwegian', nativeName: 'Norsk', script: 'Latin' },
  { code: 'or', name: 'Odia (Oriya)', nativeName: 'ଓଡ଼ିଆ', script: 'Odia' },
  { code: 'ps', name: 'Pashto', nativeName: 'پښتو', script: 'Arabic' },
  { code: 'fa', name: 'Persian', nativeName: 'فارسی', script: 'Arabic' },
  { code: 'pl', name: 'Polish', nativeName: 'Polski', script: 'Latin' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', script: 'Latin' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', script: 'Gurmukhi' },
  { code: 'ro', name: 'Romanian', nativeName: 'Română', script: 'Latin' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский', script: 'Cyrillic' },
  { code: 'sm', name: 'Samoan', nativeName: 'Gagana Sāmoa', script: 'Latin' },
  { code: 'gd', name: 'Scottish Gaelic', nativeName: 'Gàidhlig', script: 'Latin' },
  { code: 'sr', name: 'Serbian', nativeName: 'Српски', script: 'Cyrillic' },
  { code: 'sn', name: 'Shona', nativeName: 'ChiShona', script: 'Latin' },
  { code: 'sd', name: 'Sindhi', nativeName: 'سنڌي', script: 'Arabic' },
  { code: 'si', name: 'Sinhala', nativeName: 'සිංහල', script: 'Sinhala' },
  { code: 'sk', name: 'Slovak', nativeName: 'Slovenčina', script: 'Latin' },
  { code: 'sl', name: 'Slovenian', nativeName: 'Slovenščina', script: 'Latin' },
  { code: 'so', name: 'Somali', nativeName: 'Soomaaliga', script: 'Latin' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', script: 'Latin' },
  { code: 'su', name: 'Sundanese', nativeName: 'Basa Sunda', script: 'Latin' },
  { code: 'sw', name: 'Swahili', nativeName: 'Kiswahili', script: 'Latin' },
  { code: 'sv', name: 'Swedish', nativeName: 'Svenska', script: 'Latin' },
  { code: 'tg', name: 'Tajik', nativeName: 'Тоҷикӣ', script: 'Cyrillic' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', script: 'Tamil' },
  { code: 'tt', name: 'Tatar', nativeName: 'Татар теле', script: 'Cyrillic' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', script: 'Telugu' },
  { code: 'th', name: 'Thai', nativeName: 'ไทย', script: 'Thai' },
  { code: 'tr', name: 'Turkish', nativeName: 'Türkçe', script: 'Latin' },
  { code: 'tk', name: 'Turkmen', nativeName: 'Türkmen dili', script: 'Latin' },
  { code: 'uk', name: 'Ukrainian', nativeName: 'Українська', script: 'Cyrillic' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو', script: 'Arabic' },
  { code: 'ug', name: 'Uyghur', nativeName: 'ئۇيغۇرچە', script: 'Arabic' },
  { code: 'uz', name: 'Uzbek', nativeName: 'Oʻzbekcha', script: 'Latin' },
  { code: 'vi', name: 'Vietnamese', nativeName: 'Tiếng Việt', script: 'Latin' },
  { code: 'cy', name: 'Welsh', nativeName: 'Cymraeg', script: 'Latin' },
  { code: 'xh', name: 'Xhosa', nativeName: 'isiXhosa', script: 'Latin' },
  { code: 'yi', name: 'Yiddish', nativeName: 'ייִדיש', script: 'Hebrew' },
  { code: 'yo', name: 'Yoruba', nativeName: 'Èdè Yorùbá', script: 'Latin' },
  { code: 'zu', name: 'Zulu', nativeName: 'isiZulu', script: 'Latin' },
];