import { 
  NavItem, 
  HeroMetrics, 
  InteractiveCareerPath, 
  StateDiscoveryItem, 
  FeatureCard, 
  HowItWorksStep, 
  AudiencePersona, 
  CareerComparisonData, 
  PricingTier 
} from '@/types/landing';

export const NAV_ITEMS: NavItem[] = [
  { label: 'Services', href: '#services' },
  { label: 'How It Works', href: '#how-it-works' },
  { label: 'State Discovery', href: '#state-discovery' },
  // { label: 'Career Streams', href: '#comparison-preview' },
  { label: 'Pricing', href: '#pricing' },
  { label: 'Contact', href: '#contact' },
];

export const HERO_METRICS: HeroMetrics[] = [
  { label: 'Careers Mapped', value: '1,400+', subtext: 'Across 36 Streams & Diplomas' },
  { label: 'State Nuances', value: '28 States', subtext: '& 8 UT Regional Quotas Covered' },
  { label: 'Active Learners', value: '550,000+', subtext: 'Guided in 2025–2026' },
  { label: 'AI Accuracy', value: '98.4%', subtext: 'Personalized Aptitude Matching' },
];

export const HERO_CAREER_PATHS: InteractiveCareerPath[] = [
  {
    id: 'btech-cs',
    stream: 'Science (PCM)',
    title: 'Computer Science Engineering Pathway',
    targetRole: 'Senior Software Engineer / Architect',
    averageStartingSalary: '₹8.5 LPA - ₹24 LPA',
    tier1CityLifestyle: 'High savings potential in Bangalore/Hyderabad, modern tech culture.',
    tier2CityLifestyle: 'Extremely high purchasing power in Pune/Ahmedabad with lower rent.',
    steps: [
      { stage: 'Class 10th-12th', title: 'PCM Stream Focus', detail: 'Maths, Physics, Chem (>75% Board score for NIT eligibility)', duration: '2 Years' },
      { stage: 'Exams', title: 'JEE Main & Advanced / MHT-CET / KCET', detail: 'Clear national/state engineering entrance exams', duration: '6-12 Months' },
      { stage: 'Undergrad', title: 'B.Tech / B.E. Computer Science', detail: 'DSA, System Design, Full-Stack Internships', duration: '4 Years' },
      { stage: 'Outcome', title: 'SDE-1 at Tech Firm / Product Co.', detail: 'Entry role with rapid 2-year promotion cycles', duration: 'Career Start' },
    ],
  },
  {
    id: 'ca-pathway',
    stream: 'Commerce',
    title: 'Chartered Accountancy & Financial Advisory',
    targetRole: 'Chartered Accountant / Financial Controller',
    averageStartingSalary: '₹9.0 LPA - ₹18 LPA',
    tier1CityLifestyle: 'High corporate exposure in Mumbai/Delhi-NCR audit hubs.',
    tier2CityLifestyle: 'Lucrative independent practice potential with low overheads.',
    steps: [
      { stage: 'Class 12th', title: 'Commerce with Accountancy/Maths', detail: 'Strong grasp of ledger principles and statistics', duration: '2 Years' },
      { stage: 'Foundation', title: 'CA Foundation Exam', detail: '4 papers cleared after 12th boards', duration: '6 Months' },
      { stage: 'Intermediate', title: 'CA Inter & Articleship', detail: '3 years mandatory practical training under registered CA', duration: '3.5 Years' },
      { stage: 'Outcome', title: 'CA Final + ICAI Membership', detail: 'Auditing, Tax Advisory, Big 4 or Corporate Finance', duration: 'Career Start' },
    ],
  },
  {
    id: 'mbbs-pathway',
    stream: 'Science (PCB)',
    title: 'Medical Sciences & Specialization',
    targetRole: 'Consultant Doctor / Specialist Surgeon',
    averageStartingSalary: '₹7.2 LPA - ₹15 LPA (MBBS)',
    tier1CityLifestyle: 'Fast-paced clinical environment, top metro multi-specialty hospitals.',
    tier2CityLifestyle: 'High prestige and dominant clinical practice opportunities.',
    steps: [
      { stage: 'Class 12th', title: 'PCB Stream (>50% Aggregate)', detail: 'Biology, Physics, Chemistry focus', duration: '2 Years' },
      { stage: 'Entrance Exam', title: 'NEET-UG National Selection', detail: 'High target score for Govt Medical College (GMC) seats', duration: '1-2 Years Prep' },
      { stage: 'Undergrad', title: 'MBBS Degree + Internship', detail: '4.5 years academic coursework + 1 year rotatory internship', duration: '5.5 Years' },
      { stage: 'Outcome', title: 'NEET-PG / Medical Officer / Resident', detail: 'MD/MS Specialization or Clinical Practice', duration: 'Career Start' },
    ],
  },
];


export const STATE_DISCOVERY_DATA: StateDiscoveryItem[] = [
  // --- 28 STATES ---
  {
    id: 'ap',
    stateName: 'Andhra Pradesh',
    code: 'AP',
    isUnionTerritory: false,
    topEntranceExams: ['AP EAPCET', 'AP ICET', 'NEET-UG', 'AP PGECET'],
    keyColleges: ['AU College of Engineering', 'SVU Tirupati', 'IIT Tirupati', 'NIT Tadepalligudem'],
    emergingHubs: ['Visakhapatnam (IT & Pharma)', 'Vijayawada (Logistics)', 'Tirupati (Electronics)'],
    stateQuotaInsight: '85% state quota in local educational regions (AU, SVU, SKU) via AP EAPCET rank.',
    avgTuitionFeeRange: '₹45,000 - ₹1.5 Lakhs / Year (Govt/Aided)',
  },
  {
    id: 'ar',
    stateName: 'Arunachal Pradesh',
    code: 'AR',
    isUnionTerritory: false,
    topEntranceExams: ['JEE Main', 'APJEE', 'NEET-UG', 'CUET-UG'],
    keyColleges: ['NERIST Nirjuli', 'NIT Arunachal Pradesh', 'RGU Itanagar', 'TRIHMS Naharlagun'],
    emergingHubs: ['Itanagar (Govt Admin & Services)', 'Naharlagun (Healthcare & Logistics)'],
    stateQuotaInsight: '100% reservation for APST candidates in state seats with stipend support.',
    avgTuitionFeeRange: '₹20,000 - ₹60,000 / Year (Govt Inst.)',
  },
  {
    id: 'as',
    stateName: 'Assam',
    code: 'AS',
    isUnionTerritory: false,
    topEntranceExams: ['Assam CEE', 'JEE Main', 'NEET-UG'],
    keyColleges: ['AEC Guwahati', 'JEC Jorhat', 'IIT Guwahati', 'GMC Guwahati'],
    emergingHubs: ['Guwahati (Tech & Logistics Hub of NE)', 'Jorhat (Agri-Tech)', 'Dibrugarh (Energy)'],
    stateQuotaInsight: 'State CEE score governs state quota seats in engineering colleges across Assam.',
    avgTuitionFeeRange: '₹25,000 - ₹80,000 / Year (Govt/Aided)',
  },
  {
    id: 'br',
    stateName: 'Bihar',
    code: 'BR',
    isUnionTerritory: false,
    topEntranceExams: ['BCECE', 'JEE Main (UGEAC)', 'NEET-UG'],
    keyColleges: ['IIT Patna', 'NIT Patna', 'BIT Patna', 'PMCH Patna'],
    emergingHubs: ['Patna (EdTech & Civil Services)', 'Muzaffarpur (Trading)', 'Bhagalpur (Textiles)'],
    stateQuotaInsight: 'UGEAC conducts Bihar engineering counseling based on JEE Main CRL percentile.',
    avgTuitionFeeRange: '₹35,000 - ₹1.2 Lakhs / Year (Govt/Aided)',
  },
  {
    id: 'cg',
    stateName: 'Chhattisgarh',
    code: 'CG',
    isUnionTerritory: false,
    topEntranceExams: ['CG PET', 'CG Pre-MCA', 'JEE Main', 'NEET-UG'],
    keyColleges: ['IIT Bhilai', 'NIT Raipur', 'BIT Durg', 'GEC Raipur'],
    emergingHubs: ['Raipur-Bhilai (Steel & IT Parks)', 'Korba (Power Generation)'],
    stateQuotaInsight: 'CG PET handles state quota seats; JEE Main quota available for outside candidates.',
    avgTuitionFeeRange: '₹40,000 - ₹1.1 Lakhs / Year (Govt/Aided)',
  },
  {
    id: 'ga',
    stateName: 'Goa',
    code: 'GA',
    isUnionTerritory: false,
    topEntranceExams: ['GCET', 'JEE Main', 'NEET-UG'],
    keyColleges: ['BITS Pilani Goa Campus', 'GEC Farmagudi', 'NIT Goa', 'Goa Medical College'],
    emergingHubs: ['Panaji (Tourism & Tech startups)', 'Verna (Pharma & Manufacturing)'],
    stateQuotaInsight: 'Strict domicile requirements for GEC Farmagudi state seats via GCET/JEE scores.',
    avgTuitionFeeRange: '₹60,000 - ₹1.8 Lakhs / Year (Govt Inst.)',
  },
  {
    id: 'gj',
    stateName: 'Gujarat',
    code: 'GJ',
    isUnionTerritory: false,
    topEntranceExams: ['GUJCET', 'JEE Main', 'NEET-UG'],
    keyColleges: ['IIT Gandhinagar', 'SVNIT Surat', 'DA-IICT Gandhinagar', 'LD College of Engg'],
    emergingHubs: ['Ahmedabad-Gandhinagar (Fintech & IT)', 'Surat (Textiles)', 'Vadodara (Pharma)'],
    stateQuotaInsight: 'ACPC handles 95% state quota seats calculated from 50% Board PCM + 50% GUJCET scores.',
    avgTuitionFeeRange: '₹30,000 - ₹1.5 Lakhs / Year (Govt/Aided)',
  },
  {
    id: 'hr',
    stateName: 'Haryana',
    code: 'HR',
    isUnionTerritory: false,
    topEntranceExams: ['HSTES (JEE Main Merit)', 'LEET', 'NEET-UG'],
    keyColleges: ['NIT Kurukshetra', 'YMCA Faridabad', 'UIET Chandigarh', 'Pt. B.D. Sharma PGIMS'],
    emergingHubs: ['Gurugram (Enterprise SaaS & Auto)', 'Faridabad (Manufacturing)', 'Panchkula'],
    stateQuotaInsight: '85% state quota seats allocated through HSTES strictly on JEE Main All-India Rank.',
    avgTuitionFeeRange: '₹50,000 - ₹1.4 Lakhs / Year (Govt Inst.)',
  },
  {
    id: 'hp',
    stateName: 'Himachal Pradesh',
    code: 'HP',
    isUnionTerritory: false,
    topEntranceExams: ['HPCET', 'JEE Main', 'NEET-UG'],
    keyColleges: ['IIT Mandi', 'NIT Hamirpur', 'HPTU Hamirpur', 'IGMC Shimla'],
    emergingHubs: ['Baddi-Barotiwala (Asia’s Pharma Hub)', 'Shimla (Tourism & IT Services)'],
    stateQuotaInsight: '85% state seats in state universities allotted via HPCET and JEE Main scores.',
    avgTuitionFeeRange: '₹45,000 - ₹1.2 Lakhs / Year (Govt/Aided)',
  },
  {
    id: 'jh',
    stateName: 'Jharkhand',
    code: 'JH',
    isUnionTerritory: false,
    topEntranceExams: ['JCECE (JEE Main merit)', 'NEET-UG'],
    keyColleges: ['IIT (ISM) Dhanbad', 'BIT Mesra', 'NIT Jamshedpur', 'RIMS Ranchi'],
    emergingHubs: ['Jamshedpur (Steel & Heavy Industries)', 'Ranchi (Govt & Mining Tech)'],
    stateQuotaInsight: 'JCECEB conducts counseling based on JEE Main scores for government engineering colleges.',
    avgTuitionFeeRange: '₹55,000 - ₹1.6 Lakhs / Year (Govt/Aided)',
  },
  {
    id: 'ka',
    stateName: 'Karnataka',
    code: 'KA',
    isUnionTerritory: false,
    topEntranceExams: ['KCET', 'COMEDK UGET', 'PGCET'],
    keyColleges: ['IISc Bangalore', 'RVCE Bangalore', 'BMSCE', 'KMC Manipal'],
    emergingHubs: ['Bangalore (DeepTech & SaaS)', 'Mysore (ESDM)', 'Mangalore (Healthcare)'],
    stateQuotaInsight: 'KCET grants state domicile students access to subsidized government engineering & medical seats.',
    avgTuitionFeeRange: '₹65,000 - ₹3.0 Lakhs / Year (Govt Quota)',
  },
  {
    id: 'kl',
    stateName: 'Kerala',
    code: 'KL',
    isUnionTerritory: false,
    topEntranceExams: ['KEAM', 'NEET-UG'],
    keyColleges: ['NIT Calicut', 'College of Engineering Trivandrum (CET)', 'IIT Palakkad', 'GMC Trivandrum'],
    emergingHubs: ['Kochi (Fintech & IT Parks)', 'Trivandrum (SpaceTech & SaaS)', 'Kozhikode'],
    stateQuotaInsight: 'KEAM rank is calculated by combining 12th Board PCM marks and KEAM Entrance exam marks 50:50.',
    avgTuitionFeeRange: '₹35,000 - ₹90,000 / Year (Govt/Aided)',
  },
  {
    id: 'mp',
    stateName: 'Madhya Pradesh',
    code: 'MP',
    isUnionTerritory: false,
    topEntranceExams: ['MP PET (JEE Main merit via MP DTE)', 'CUET-UG', 'NEET-UG'],
    keyColleges: ['IIT Indore', 'MANIT Bhopal', 'SGSITS Indore', 'SMMC Bhopal'],
    emergingHubs: ['Indore (IT Parks & Clean Tech)', 'Bhopal (Manufacturing & Public Sector)'],
    stateQuotaInsight: 'MP DTE handles 90% state domicile reservation via JEE Main scores across state institutions.',
    avgTuitionFeeRange: '₹45,000 - ₹1.3 Lakhs / Year (Govt Inst.)',
  },
  {
    id: 'mh',
    stateName: 'Maharashtra',
    code: 'MH',
    isUnionTerritory: false,
    topEntranceExams: ['MHT-CET', 'JEE Main', 'NEET-UG', 'PERA CET'],
    keyColleges: ['COEP Pune', 'VJTI Mumbai', 'ICT Mumbai', 'Fergusson College'],
    emergingHubs: ['Pune (IT & Auto)', 'Mumbai (BFSI & Media)', 'Nagpur (Logistics)'],
    stateQuotaInsight: '85% State Quota in State Govt Colleges via MHT-CET score.',
    avgTuitionFeeRange: '₹80,000 - ₹2.5 Lakhs / Year (Govt/Aided)',
  },
  {
    id: 'mn',
    stateName: 'Manipur',
    code: 'MN',
    isUnionTerritory: false,
    topEntranceExams: ['JEE Main', 'NEET-UG', 'CUET-UG'],
    keyColleges: ['NIT Manipur', 'IIIT Manipur', 'Central Agricultural University Imphal', 'RIMS Imphal'],
    emergingHubs: ['Imphal (Handloom, Agri-Exports & Healthcare)'],
    stateQuotaInsight: 'State quota seats in NIT Manipur and RIMS are strictly reserved for Manipur domiciles.',
    avgTuitionFeeRange: '₹25,000 - ₹70,000 / Year (Govt Inst.)',
  },
  {
    id: 'ml',
    stateName: 'Meghalaya',
    code: 'ML',
    isUnionTerritory: false,
    topEntranceExams: ['JEE Main', 'NEET-UG', 'CUET-UG'],
    keyColleges: ['IIM Shillong', 'NIT Meghalaya', 'NEHU Shillong', 'NEIGRIHMS'],
    emergingHubs: ['Shillong (Education & Tourism Hub)'],
    stateQuotaInsight: 'State nomination seats for B.Tech/MBBS are allocated based on JEE/NEET merit.',
    avgTuitionFeeRange: '₹30,000 - ₹80,000 / Year (Govt Inst.)',
  },
  {
    id: 'mz',
    stateName: 'Mizoram',
    code: 'MZ',
    isUnionTerritory: false,
    topEntranceExams: ['JEE Main', 'NEET-UG', 'CUET-UG'],
    keyColleges: ['NIT Mizoram', 'Mizoram University (MZU)', 'ZMC Aizawl'],
    emergingHubs: ['Aizawl (Bamboo Tech & Tourism)'],
    stateQuotaInsight: 'Home state quota in NIT Mizoram gives local students preferential admission cutoffs.',
    avgTuitionFeeRange: '₹20,000 - ₹65,000 / Year (Govt Inst.)',
  },
  {
    id: 'nl',
    stateName: 'Nagaland',
    code: 'NL',
    isUnionTerritory: false,
    topEntranceExams: ['JEE Main', 'NSEE', 'NEET-UG'],
    keyColleges: ['NIT Nagaland', 'Nagaland University Lumami', 'SETAM Dimapur'],
    emergingHubs: ['Dimapur (Commercial Center)', 'Kohima (Administrative & Education)'],
    stateQuotaInsight: 'NSEE exam and JEE Main rank combined control reserved state technical seats.',
    avgTuitionFeeRange: '₹25,000 - ₹75,000 / Year (Govt Inst.)',
  },
  {
    id: 'od',
    stateName: 'Odisha',
    code: 'OD',
    isUnionTerritory: false,
    topEntranceExams: ['OJEE', 'JEE Main', 'NEET-UG'],
    keyColleges: ['IIT Bhubaneswar', 'NIT Rourkela', 'OUTR Bhubaneswar', 'VSSUT Burla'],
    emergingHubs: ['Bhubaneswar (IT & Education Hub)', 'Rourkela (Metallurgy)', 'Jharsuguda'],
    stateQuotaInsight: 'OJEE conducts web counseling for 85% state seats based on JEE Main CRL.',
    avgTuitionFeeRange: '₹40,000 - ₹1.2 Lakhs / Year (Govt/Aided)',
  },
  {
    id: 'pb',
    stateName: 'Punjab',
    code: 'PB',
    isUnionTerritory: false,
    topEntranceExams: ['JEE Main (PTU Counseling)', 'NEET-UG'],
    keyColleges: ['IIT Ropar', 'Thapar Institute Patiala', 'GNDEC Ludhiana', 'SLIET Longowal'],
    emergingHubs: ['Mohali (IT & Telecom)', 'Ludhiana (Textiles & Auto Components)', 'Jalandhar'],
    stateQuotaInsight: '85% state quota seats in IKGPTU and MRSPTU filled via JEE Main scores.',
    avgTuitionFeeRange: '₹60,000 - ₹1.8 Lakhs / Year (Govt/Aided)',
  },
  {
    id: 'rj',
    stateName: 'Rajasthan',
    code: 'RJ',
    isUnionTerritory: false,
    topEntranceExams: ['REAP (JEE Main / 12th Merit)', 'REAP Architecture', 'NEET-UG'],
    keyColleges: ['IIT Jodhpur', 'MNIT Jaipur', 'MBM Jodhpur', 'RTU Kota'],
    emergingHubs: ['Jaipur (SaaS & Handicrafts)', 'Kota (Coaching Economy)', 'Jodhpur (Solar & Defense)'],
    stateQuotaInsight: 'REAP handles state engineering counseling based on JEE Main scores followed by Class 12th marks.',
    avgTuitionFeeRange: '₹55,000 - ₹1.4 Lakhs / Year (Govt Inst.)',
  },
  {
    id: 'sk',
    stateName: 'Sikkim',
    code: 'SK',
    isUnionTerritory: false,
    topEntranceExams: ['JEE Main', 'NEET-UG', 'CUET-UG'],
    keyColleges: ['NIT Sikkim', 'Sikkim Manipal Institute of Technology (SMIT)', 'Sikkim University'],
    emergingHubs: ['Gangtok (Tourism & Eco-Tech)', 'Rangpo (Pharma Hub)'],
    stateQuotaInsight: '20% to 50% state fee concessions available for Sikkim domicile holders at SMIT.',
    avgTuitionFeeRange: '₹30,000 - ₹1.5 Lakhs / Year (Govt Quota)',
  },
  {
    id: 'tn',
    stateName: 'Tamil Nadu',
    code: 'TN',
    isUnionTerritory: false,
    topEntranceExams: ['TNEA (12th Marks Cutoff)', 'TANCET', 'NEET-UG'],
    keyColleges: ['Anna University (CEG)', 'PSG Tech Coimbatore', 'IIT Madras', 'MCC Chennai'],
    emergingHubs: ['Chennai (SaaS & Automotive)', 'Coimbatore (Textiles & Tech)', 'Madurai'],
    stateQuotaInsight: 'No state entrance test for Engineering; TNEA rank derived strictly from Class 12 PCM scores.',
    avgTuitionFeeRange: '₹50,000 - ₹1.8 Lakhs / Year (Govt/Aided)',
  },
  {
    id: 'tg',
    stateName: 'Telangana',
    code: 'TG',
    isUnionTerritory: false,
    topEntranceExams: ['TG EAPCET', 'TG ICET', 'JEE Main', 'NEET-UG'],
    keyColleges: ['IIT Hyderabad', 'NIT Warangal', 'JNTU Hyderabad', 'CBR IT Gandipet'],
    emergingHubs: ['Hyderabad (Genome Valley & HITEC City)', 'Warangal (Tier-2 Tech Expansion)'],
    stateQuotaInsight: '85% local candidate quota under TG EAPCET across Osmania & JNTU regions.',
    avgTuitionFeeRange: '₹50,000 - ₹2.2 Lakhs / Year (Govt/Aided)',
  },
  {
    id: 'tr',
    stateName: 'Tripura',
    code: 'TR',
    isUnionTerritory: false,
    topEntranceExams: ['TJEE', 'JEE Main', 'NEET-UG'],
    keyColleges: ['NIT Agartala', 'TIT Narsingarh', 'Tripura University', 'AGMC Agartala'],
    emergingHubs: ['Agartala (Border Trade & Public Services)'],
    stateQuotaInsight: 'TJEE ranks govern admission to Tripura state engineering and professional colleges.',
    avgTuitionFeeRange: '₹25,000 - ₹70,000 / Year (Govt Inst.)',
  },
  {
    id: 'up',
    stateName: 'Uttar Pradesh',
    code: 'UP',
    isUnionTerritory: false,
    topEntranceExams: ['CUET-UG', 'JEE Main (UPTAC Counselling)', 'NEET-UG'],
    keyColleges: ['IIT Kanpur', 'BHU Varanasi', 'IET Lucknow', 'HBTU Kanpur'],
    emergingHubs: ['Noida/Greater Noida (IT & Electronics)', 'Lucknow (Govt & Defense)'],
    stateQuotaInsight: 'UPTAC handles state seat allocation for technical universities using JEE Main NTA scores.',
    avgTuitionFeeRange: '₹70,000 - ₹1.5 Lakhs / Year (Govt Inst.)',
  },
  {
    id: 'uk',
    stateName: 'Uttarakhand',
    code: 'UK',
    isUnionTerritory: false,
    topEntranceExams: ['UKSEE', 'JEE Main (UTU Counseling)', 'NEET-UG'],
    keyColleges: ['IIT Roorkee', 'G.B. Pant University Pantnagar', 'NIT Uttarakhand', 'VMSUT Dehradun'],
    emergingHubs: ['Dehradun (Higher Ed & IT Hub)', 'Haridwar-Pantnagar (Industrial Belts)'],
    stateQuotaInsight: 'UTU counseling reserves 85% of seats for Uttarakhand domicile candidates via JEE Main.',
    avgTuitionFeeRange: '₹45,000 - ₹1.2 Lakhs / Year (Govt Inst.)',
  },
  {
    id: 'wb',
    stateName: 'West Bengal',
    code: 'WB',
    isUnionTerritory: false,
    topEntranceExams: ['WBJEE', 'JEE Main', 'NEET-UG', 'JECA'],
    keyColleges: ['IIT Kharagpur', 'Jadavpur University', 'JU Salt Lake', 'Calcutta Medical College'],
    emergingHubs: ['Kolkata (Salt Lake Sector V & New Town Tech Hub)', 'Durgapur (Heavy Engineering)'],
    stateQuotaInsight: 'Jadavpur University & State colleges offer 90%+ seats strictly via WBJEE domicile rank.',
    avgTuitionFeeRange: '₹10,000 - ₹50,000 / Year (Jadavpur/Govt Rate)',
  },

  // --- 8 UNION TERRITORIES ---
  {
    id: 'an',
    stateName: 'Andaman & Nicobar Islands',
    code: 'AN',
    isUnionTerritory: true,
    topEntranceExams: ['JEE Main', 'NEET-UG', 'CUET-UG'],
    keyColleges: ['DBRAIT Port Blair', 'ANIIMS Port Blair', 'JNRM Port Blair'],
    emergingHubs: ['Port Blair (Ecotourism, Maritime & Defense)'],
    stateQuotaInsight: '100% reservation for island domiciles in DBRAIT diploma and degree technical programs.',
    avgTuitionFeeRange: '₹15,000 - ₹45,000 / Year (Govt Inst.)',
  },
  {
    id: 'ch',
    stateName: 'Chandigarh',
    code: 'CH',
    isUnionTerritory: true,
    topEntranceExams: ['JAC Chandigarh (JEE Main)', 'NEET-UG'],
    keyColleges: ['PEC Chandigarh', 'UIET Panjab University', 'GMCH Sector 32'],
    emergingHubs: ['Chandigarh (IT Park & Defense R&D)'],
    stateQuotaInsight: '85% UT Quota reserved for candidates who passed Class 12th from Chandigarh schools.',
    avgTuitionFeeRange: '₹70,000 - ₹1.8 Lakhs / Year',
  },
  {
    id: 'dn',
    stateName: 'Dadra & Nagar Haveli and Daman & Diu',
    code: 'DN',
    isUnionTerritory: true,
    topEntranceExams: ['JEE Main', 'GUJCET', 'NEET-UG'],
    keyColleges: ['Government Engineering College Daman', 'Dr. BBR Govt Poly Silvassa'],
    emergingHubs: ['Silvassa (Manufacturing)', 'Daman (Pharma & Plastics)'],
    stateQuotaInsight: 'Reserved UT quotas in neighboring Gujarat engineering & medical institutions.',
    avgTuitionFeeRange: '₹20,000 - ₹50,000 / Year (Govt Inst.)',
  },
  {
    id: 'dl',
    stateName: 'Delhi',
    code: 'DL',
    isUnionTerritory: true,
    topEntranceExams: ['JAC Delhi (JEE Main)', 'CUET-UG', 'IPU CET'],
    keyColleges: ['DTU Delhi', 'NSUT Delhi', 'IIT Delhi', 'SRCC Delhi University'],
    emergingHubs: ['Gurugram (Corporate HQ)', 'Noida (GCCs & Media)', 'Delhi Center'],
    stateQuotaInsight: '85% reserved quota for candidates passing Class 12th from Delhi schools under JAC Delhi.',
    avgTuitionFeeRange: '₹1.2 Lakhs - ₹2.4 Lakhs / Year',
  },
  {
    id: 'jk',
    stateName: 'Jammu & Kashmir',
    code: 'JK',
    isUnionTerritory: true,
    topEntranceExams: ['JKCET (BOPEE)', 'JEE Main', 'NEET-UG'],
    keyColleges: ['NIT Srinagar', 'IIT Jammu', 'GCET Jammu', 'GMC Srinagar'],
    emergingHubs: ['Srinagar (Services & Tourism)', 'Jammu (Trade & Education)'],
    stateQuotaInsight: 'BOPEE conducts Jammu & Kashmir state counseling for engineering and medical seats.',
    avgTuitionFeeRange: '₹30,000 - ₹90,000 / Year (Govt Inst.)',
  },
  {
    id: 'la',
    stateName: 'Ladakh',
    code: 'LA',
    isUnionTerritory: true,
    topEntranceExams: ['JEE Main', 'NEET-UG', 'CUET-UG'],
    keyColleges: ['University of Ladakh', 'EJM College Leh', 'Govt Degree College Kargil'],
    emergingHubs: ['Leh (Solar Energy & Ecotourism)', 'Kargil (Trade Route Hub)'],
    stateQuotaInsight: 'Special reserved central quotas allocated for Ladakh students in top NITs/IITs nationwide.',
    avgTuitionFeeRange: '₹10,000 - ₹35,000 / Year (Govt Inst.)',
  },
  {
    id: 'ld',
    stateName: 'Lakshadweep',
    code: 'LD',
    isUnionTerritory: true,
    topEntranceExams: ['JEE Main', 'NEET-UG', 'KEAM Seats'],
    keyColleges: ['Calicut University Center Kavaratti', 'Govt Arts & Science Kadmat'],
    emergingHubs: ['Kavaratti (Marine Ecosystem & Hospitality)'],
    stateQuotaInsight: 'Reserved seats for islanders in Kerala medical & engineering colleges under UT quota.',
    avgTuitionFeeRange: '₹10,000 - ₹30,000 / Year (Govt Quota)',
  },
  {
    id: 'py',
    stateName: 'Puducherry',
    code: 'PY',
    isUnionTerritory: true,
    topEntranceExams: ['CENTAC (JEE Main / 12th Merit)', 'NEET-UG'],
    keyColleges: ['JIPMER Puducherry', 'Puducherry Technological University (PTU)', 'PEC'],
    emergingHubs: ['Puducherry (Biotech, IT & French Heritage Tourism)'],
    stateQuotaInsight: 'CENTAC handles central counseling with dedicated residence quotas for Puducherry locals.',
    avgTuitionFeeRange: '₹40,000 - ₹1.1 Lakhs / Year (Govt/Aided)',
  },
];

export const KEY_SERVICES: FeatureCard[] = [
  {
    id: 'ai-roadmap',
    iconName: 'Compass',
    title: 'AI Career Roadmap Generator',
    description: 'Generates step-by-step educational & milestone maps from Class 9th through your first 5 years in the workforce.',
    badge: 'AI Powered',
    highlights: ['Subject combination advice', 'Entrance exam timelines', 'Skill gap analyzer'],
  },
  {
    id: 'regional-engine',
    iconName: 'MapPin',
    title: 'Regional & Domicile Engine',
    description: 'Understand state reservation quotas, local entrance CET cutoffs, state scholarship schemes, and local job market growth.',
    highlights: ['State Quota breakdown', 'Local entrance exam prep paths', 'Tier-2/3 college ratings'],
  },
  {
    id: 'side-by-side',
    iconName: 'GitCompare',
    title: '360° Career & Lifestyle Comparator',
    description: 'Compare 2 to 5 careers across starting pay, 10-year growth ceiling, work-life balance, exam difficulty, and living costs.',
    highlights: ['Salary distribution charts', 'Stress & lifestyle index', 'Cost of education vs ROI'],
  },
  {
    id: 'roi-calculator',
    iconName: 'Calculator',
    title: 'Tier 1/2/3 Living Cost & ROI Calculator',
    description: 'Model real disposable income after rent, taxes, and loan EMIs in Bangalore, Mumbai, Pune, vs hometown setups.',
    badge: 'Popular',
    highlights: ['Education loan EMI calculator', 'City cost of living index', 'Net disposable income preview'],
  },
  {
    id: 'parent-portal',
    iconName: 'Users',
    title: 'Dual Student & Parent Dashboards',
    description: 'Transparent views for parents covering realistic budget planning, exam safety margins, and verified career security metrics.',
    highlights: ['Budget feasibility insights', 'Exam stress trackers', 'Mentor-verified advice'],
  },
  {
    id: 'exam-tracker',
    iconName: 'CalendarCheck',
    title: 'National & State Exam Alerts',
    description: 'Never miss application deadlines for JEE, NEET, CUET, CLAT, CAT, UPSC, or regional state entrance exams.',
    highlights: ['Instant WhatsApp/Email alerts', 'Eligibility checker', 'Syllabus & pattern updates'],
  },
];

export const HOW_IT_WORKS_STEPS: HowItWorksStep[] = [
  {
    stepNumber: '01',
    title: 'Select State, Stream & Grade',
    description: 'Tell us your current academic standing, preferred streams, and your state of eligibility/domicile.',
    details: ['Class 9th-12th or Undergrad status', 'State board or CBSE/ICSE alignment', 'Financial preferences'],
  },
  {
    stepNumber: '02',
    title: ' Aptitude & Interest Profiler',
    description: 'A 10-minute scientifically validated quiz mapping your analytical, creative, and administrative inclinations.',
    details: ['No prior preparation needed', 'Bilingual options (English & Regional)', 'Identifies hidden career fits'],
  },
  {
    stepNumber: '03',
    title: 'Explore Tailored Roadmaps & ROI',
    description: 'Get clear visual paths detailing every exam, degree option, fee structure, and expected lifestyle upon graduation.',
    details: ['Compare alternative backup paths', 'Calculates education loan viability', 'Clear entry vs peak salary metrics'],
  },
  {
    stepNumber: '04',
    title: 'Execute & Track Progress',
    description: 'Bookmark target target colleges, track exam application windows, and access verified study resources.',
    details: ['Personalized milestone dashboard', 'Direct mentor booking available', 'Regular exam alert notifications'],
  },
];

export const AUDIENCE_PERSONAS: AudiencePersona[] = [
  {
    id: 'students-school',
    roleTitle: 'High School Students (9th - 12th)',
    tagline: 'Choose the right stream & entrance exams without peer pressure.',
    painPoints: ['Confused between PCM, PCB, Commerce, and Arts', 'Fearing wrong stream choices', 'Overwhelmed by exam syllabus'],
    keySolutions: ['Visual 5-year step-by-step milestone roadmaps', 'Stream-fit AI diagnostic tests', 'Comprehensive exam calendar'],
    ctaText: 'Discover Your Best Stream',
  },
  {
    id: 'students-ug',
    roleTitle: 'Undergraduates & College Graduates',
    tagline: 'Navigate post-grad degrees, Govt exams, or private market tech skills.',
    painPoints: ['Uncertain about placement market reality', 'Should I do MBA, M.Tech, or enter corporate?', 'Is UPSC/Govt exam worth the years?'],
    keySolutions: ['ROI comparisons across MBA vs M.Tech vs Corporate', 'Tier-1 vs Tier-2 tech hub relocation guides', 'Skill gap roadmaps'],
    ctaText: 'Map Your Post-Grad Career',
  },
  {
    id: 'parents',
    roleTitle: 'Parents & Guardians',
    tagline: 'Make informed financial and educational investments for your child.',
    painPoints: ['High college tuition vs uncertain job outcomes', 'Lack of awareness of modern non-traditional careers', 'Managing child stress'],
    keySolutions: ['Transparent tuition fee vs expected starting salary charts', 'Verified safety & stability metrics', 'Parent-friendly summary reports'],
    ctaText: 'Explore Parent Guidance Dashboard',
  },
  {
    id: 'counsellors',
    roleTitle: 'Schools & Career Counsellors',
    tagline: 'Empower your institution with real-time Indian career telemetry.',
    painPoints: ['Outdated static career charts', 'Manual student tracking overhead', 'Lack of state-specific quota data'],
    keySolutions: ['Admin panel for bulk student roadmap tracking', 'Automated progress reports', 'Exportable PDF career guides'],
    ctaText: 'Partner with CareerMapFinder',
  },
];

export const COMPARISON_DATA: CareerComparisonData[] = [
  {
    id: 'sde',
    careerName: 'Software Engineering (Product)',
    stream: 'Science (PCM)',
    avgPreparationTime: '4 Years (B.Tech / B.E)',
    topExams: ['JEE Main', 'JEE Advanced', 'BITSAT', 'MHT-CET'],
    avgTuitionCost: '₹4.0 L - ₹12.0 L',
    startingSalaryTier1: '₹10.0 LPA - ₹22.0 LPA',
    startingSalaryTier2: '₹5.5 LPA - ₹10.0 LPA',
    workLifeBalanceScore: 7,
    growthRate: '24% YoY (High)',
    lifestyleTier1: 'High tech salary, high rent in Bangalore/Gurgaon, fast upward mobility.',
  },
  {
    id: 'ca',
    careerName: 'Chartered Accountancy (CA)',
    stream: 'Commerce',
    avgPreparationTime: '4.5 - 5 Years',
    topExams: ['CA Foundation', 'CA Inter', 'CA Final'],
    avgTuitionCost: '₹1.5 L - ₹3.5 L (Self-study + Coaching)',
    startingSalaryTier1: '₹9.0 LPA - ₹16.0 LPA',
    startingSalaryTier2: '₹6.5 LPA - ₹11.0 LPA',
    workLifeBalanceScore: 6,
    growthRate: '18% YoY (Stable)',
    lifestyleTier1: 'Intense tax season hours in tier-1 corporate audit firms; strong job security.',
  },
  {
    id: 'data-science',
    careerName: 'Data Analytics & AI Engineering',
    stream: 'Science (PCM)',
    avgPreparationTime: '3 - 4 Years (B.Sc / B.Tech)',
    topExams: ['CUET-UG', 'JEE Main', 'ISI Admission Test'],
    avgTuitionCost: '₹3.0 L - ₹10.0 L',
    startingSalaryTier1: '₹8.5 LPA - ₹18.0 LPA',
    startingSalaryTier2: '₹5.0 LPA - ₹9.0 LPA',
    workLifeBalanceScore: 8,
    growthRate: '32% YoY (Very High)',
    lifestyleTier1: 'Hybrid work options in GCCs and tech startups; emphasis on continuous learning.',
  },
  {
    id: 'mbbs',
    careerName: 'Doctor / Medical Officer (MBBS)',
    stream: 'Science (PCB)',
    avgPreparationTime: '5.5 Years + 3 Yrs PG',
    topExams: ['NEET-UG', 'NEET-PG'],
    avgTuitionCost: '₹1.0 L - ₹6.0 L (Govt) / ₹50 L+ (Pvt)',
    startingSalaryTier1: '₹7.5 LPA - ₹14.0 LPA',
    startingSalaryTier2: '₹6.0 LPA - ₹11.0 LPA',
    workLifeBalanceScore: 4,
    growthRate: '15% YoY (Immense Resilience)',
    lifestyleTier1: 'Demanding shift duties early on; ultimate social respect and lifelong security.',
  },
];

export const PRICING_TIERS: PricingTier[] = [
  {
    id: 'free',
    name: 'Explorer (Free)',
    priceMonthly: 0,
    priceAnnual: 0,
    description: 'Essential career exploration for students starting their discovery journey.',
    features: [
      'Access to 1000+ Career Profiles',
      'Basic State Entrance Exam Directory',
      '1 AI Stream Diagnostic Assessment',
      'Community Q&A Forum Access',
      'Standard Mobile & Desktop View',
    ],
    ctaText: 'Start Exploring Free',
  },
  {
    id: 'pro-student',
    name: 'Pro Student Roadmap',
    popular: true,
    priceMonthly: 299,
    priceAnnual: 2499,
    description: 'Complete personalized guidance package for serious applicants and exam takers.',
    features: [
      'Unlimited AI Career Roadmap Generation',
      'Full 28-State Quota & CET Cutoff Insights',
      'Side-by-Side 5-Career Comparator',
      'Tier 1/2/3 ROI & Living Cost Calculator',
      'Instant SMS & WhatsApp Exam Deadline Alerts',
      'Downloadable PDF Career Blueprints',
    ],
    ctaText: 'Unlock Pro Student Pass',
  },
  {
    id: 'parent-mentor',
    name: 'Parent & Mentor Suite',
    priceMonthly: 599,
    priceAnnual: 4999,
    description: 'Advanced family financial planning, college safety metrics, and 1-on-1 expert sessions.',
    features: [
      'Everything in Pro Student Pass',
      'Dual Parent Dashboard with Financial Estimators',
      'College Tuition vs ROI Analysis Reports',
      '1 Free 30-Min Expert Mentor Consultation Call',
      'Direct WhatsApp Priority Helpdesk',
      'Multi-child profile tracking (Up to 3 students)',
    ],
    ctaText: 'Get Parent Suite',
  },
];

export const FOOTER_LINKS = {
  popularStreams: [
    { name: 'Computer Science & IT', href: '#' },
    { name: 'MBBS & Allied Health', href: '#' },
    { name: 'Law & Judiciary (CLAT)', href: '#' },
  ],
  statesCovered: [
    { name: 'Go home page', href: '#' },
    { name: 'Pricing Page', href: '#pricing' },
    { name: 'Contact page', href: '#contact' },
  ],
  tools: [
    { name: 'Key Services', href: '#services' },
    { name: 'How It Works', href: '#how-it-works' },
    { name: 'State Discovery', href: '#state-discovery' },
  ],
  legal: [
    { name: 'Privacy Policy', href: '/privacy' },
    { name: 'Terms of Service', href: '/terms' },
    { name: 'Create New Account', href: '/auth/signup' },
  ],
};