import { ComprehensiveCareerReport } from './careerExplorer';

export const sampleProductionCareerReport: ComprehensiveCareerReport[] = [

  // ==========================================
  // PROFILE 1: CORPORATE LAWYER & LITIGATOR (India Home -> Global Mobility)
  // ==========================================
  {
    id: 'report_clx_98471204',
    intakeId: 'intake_clx_0019284',
    careerName: 'Corporate Lawyer & Litigation Specialist',
    careerOverview: `A Legal Professional in India specializes either in Corporate Law (M&A, cross-border restructuring, technology contracts) or High Court/Supreme Court Litigation. Corporate lawyers structure billion-dollar transactions for conglomerates, private equity firms, and Tech startups, while Litigators represent clients in complex dispute resolutions, constitutional matters, and international arbitration.`,
    whatProfessionalDoes: `• Draft, review, and negotiate complex M&A agreements, joint ventures, and shareholder rights.
• Conduct legal due diligence for corporate acquisitions, venture funding rounds, and IPOs.
• Formulate litigation strategies for High Courts, National Company Law Tribunal (NCLT), and the Supreme Court of India.
• Represent multinational corporations in cross-border commercial arbitration (SIAC, LCIA).`,
    whyChooseThisCareer: `Offers high societal influence, intellectual rigor, and direct access to top corporate leadership. Fresh graduates from Tier-1 NLUs entering Tier-1 law firms start at compensation tiers competitive with top engineering roles.`,
    whoIsSuitableFor: `Individuals with superior analytical reasoning, persuasive oral/written advocacy, high reading stamina, and acute attention to contractual nuances.`,
    requiredSkills: [
      'Legal Drafting & Contract Analysis',
      'Corporate Mergers & Acquisitions Structuring',
      'Cross-Border International Arbitration',
      'Negotiation & Oral Advocacy',
      'Regulatory Compliance (SEBI, RBI, CCI)',
    ],
    importantSubjects: [
      'Constitutional Law',
      'Law of Contracts & Torts',
      'Corporate & Company Law',
      'Intellectual Property Rights',
    ],
    workEnvironmentDesc: 'Tier-1 Law Firm corporate suites, litigation chambers at High Courts/Supreme Court, or in-house legal departments.',
    typicalDayLife: `• 09:30 AM: Review draft Shareholders' Agreement (SHA) for a Series B financing round.
• 11:30 AM: Appear before the High Court / NCLT bench for interim stay argument.
• 03:00 PM: Client negotiation call between Indian founders and international venture capital partners.
• 06:30 PM: Deep research on precedent judgments for an ongoing cross-border tax dispute.`,
    class10Requirements: 'Minimum 50% aggregate score in any recognized board (CBSE, ICSE, State Boards).',
    class11_12Stream: 'Open to All Streams (Humanities, Commerce, or Science) with strong proficiency in English.',
    subjectsRequired: ['English Literature/Language', 'Political Science / Commerce (Optional but beneficial)'],
    minQualification: 'BACHELORS',
    ageLimit: 'No upper age limit for CLAT UG or AILET exams.',
    nationalityEligibility: 'Indian Nationals, NRIs, OCIs, and Foreign Nationals.',
    medicalRequirements: 'Standard physical requirements; no specialized medical clearance needed.',
    courseOptions: [
      '5-Year Integrated B.A. LL.B. (Hons.) / B.B.A. LL.B. (Hons.)',
      '3-Year LL.B. (Post Graduation)',
      '1-Year Master of Laws (LL.M.)',
    ],
    courseDuration: '5 Years (Integrated Dual Degree after Class 12) OR 3 Years (after graduation)',
    degreeRequired: 'B.A. LL.B. (Hons.) or LL.B. recognized by the Bar Council of India (BCI)',
    entranceExams: ['CLAT UG (Consortium of NLUs)', 'AILET (NLU Delhi)', 'SLAT (Symbiosis)', 'MHCET Law', 'LSAT India'],
    nationalExams: ['CLAT UG (Common Law Admission Test)', 'AILET (All India Law Entrance Test)'],
    stateExams: ['MH CET Law (5-Year & 3-Year)', 'AP LAWCET', 'TS LAWCET'],
    universityExams: ['SLAT (Symbiosis Law School)', 'NMIMS LAT', 'Christ University Law Entrance'],
    examEligibility: 'Class 12 / 10+2 pass with minimum 45% aggregate (40% for SC/ST reserved categories).',
    examPattern: '120 Multiple Choice Questions (MCQs) testing comprehension-based passages in 2 Hours (120 Minutes).',
    examSubjects: ['Legal Reasoning', 'Logical Reasoning', 'Reading Comprehension (English)', 'Current Affairs & GK', 'Quantitative Techniques'],
    numberOfQuestions: 120,
    markingScheme: '+1.0 mark for correct answer, -0.25 mark penalty for wrong response',
    examFrequency: 'Once Annually (Usually held in December for academic session starting July)',
    applicationProcess: 'Online registration on consortiumofnlus.ac.in portal, filling choice preferences for 25 NLUs, uploading credentials, and fee payment.',
    applicationFees: '₹4,000 for General/OBC; ₹3,500 for SC/ST/BPL',
    importantDates: 'August - November (Application Window); December (CLAT Exam Day); January - May (Counselling Rounds)',
    prepStrategy: 'Master speed reading and analytical comprehension. Practice daily passage-based legal logic questions and maintain 12 months of structured current affairs notes.',
    recommendedBooks: [
      'Word Power Made Easy by Norman Lewis',
      'Legal Aptitude for the CLAT by AP Bhardwaj',
      'Universal\'s Guide to CLAT & LL.B. Entrance Examination',
    ],
    prepTimeline: '12 Months (Class 12 starting phase).',
    admissionProcess: 'Centralised Seat Allotment via CLAT counseling merit ranks, document verification, and admission confirmation at allotted NLU.',
    counsellingProcess: '5 Rounds of online centralized seat selection managed by the Consortium of National Law Universities.',
    quotaReservations: 'State Domicile Quota (25-50% in most NLUs), SC (15%), ST (7.5%), OBC-NCL (27%), EWS (10%), PwD (5%).',
    topGovtColleges: [
      'National Law School of India University (NLSIU), Bengaluru',
      'NALSAR University of Law, Hyderabad',
      'The West Bengal National University of Juridical Sciences (WBNUJS), Kolkata',
      'National Law University (NLU), Delhi',
      'Gujarat National Law University (GNLU), Gandhinagar',
    ],
    topPrivateColleges: [
      'Jindal Global Law School (JGLS), Sonipat',
      'Symbiosis Law School (SLS), Pune',
      'ILS Law College, Pune',
    ],
    collegeSelectionGuide: 'Prioritize Tier-1 NLUs (NLSIU, NALSAR, NUJS, NLU Delhi) for 90%+ institutional campus placements at Tier-1 corporate law firms.',
    expectedCutoffs: 'Rank Under 100 for NLSIU Bengaluru (General Category); Rank Under 350 for Top 3 NLUs.',
    feeStructure: 'NLUs: ₹2.5 Lakhs - ₹3.5 Lakhs / Year | Top Private (Jindal): ₹6 Lakhs - ₹9 Lakhs / Year',
    availableScholarships: [
      'Aditya Birla Scholarship for Law Students',
      'Central Sector Scheme of Scholarships for College Students',
      'NLU Merit-cum-Means Tuition Fee Waivers',
    ],
    stepByStepRoadmap: `Step 1: Clear CLAT UG / AILET exam with top merit rank in Class 12.
Step 2: Complete 5-Year B.A. LL.B. (Hons.) program with internships each semester.
Step 3: Clear the All India Bar Examination (AIBE) conducted by BCI to obtain permanent practicing license.
Step 4: Join Tier-1 Law Firm as Associate OR join Senior Advocate chambers for litigation.
Step 5: Progress to Senior Associate (3-5 Yrs), Principal Associate (6-8 Yrs), Partner (9+ Yrs).`,
    internshipRequirements: 'Mandatory 20 weeks of internships over 5 years (under Advocates, NGOs, Law Firms, Judiciaries, and Corporate Legal Cells).',
    licensingRegistration: 'State Bar Council Enrollment followed by clearing All India Bar Examination (AIBE) within 2 years.',
    entryLevelRoles: ['Junior Law Firm Associate', 'Litigation Junior Advocate', 'In-House Legal Management Trainee'],
    midLevelRoles: ['Senior Law Associate', 'In-House Legal Counsel', 'Independent High Court Practitioner'],
    seniorLevelRoles: ['Equity Partner (Law Firm)', 'General Counsel (GC)', 'Designated Senior Advocate', 'High Court / Supreme Court Judge'],
    specializations: ['Corporate Mergers & Acquisitions', 'Intellectual Property & Technology Law', 'Commercial Arbitration', 'Taxation Law'],
    superSpecializations: ['Cross-Border International Disputes', 'Aviation & Maritime Law', 'Fintech & Algorithmic Law'],
    higherEducationPaths: ['LL.M. at Oxford/Cambridge/Harvard (BCL/LLM)', 'Ph.D. in Law'],
    alternativeCareerPaths: ['Judicial Services (Civil Judge Examination)', 'Civil Services (IAS/IFS)', 'Legal Tech Product Management'],
    govtJobOpportunities: 'Judicial Officers (Civil Judge Class I), Public Prosecutors, Legal Officers in PSUs (ONGC, IOCL, SEBI, RBI).',
    privateJobOpportunities: 'Tier-1 & Tier-2 Corporate Law Firms, Multinational Corporations, Fintech Giants, Investment Banks.',
    selfEmploymentOptions: 'Independent Chamber Practice at High Courts / Supreme Court or legal consultancy firm.',
    hiringIndustries: ['Legal Services & Arbitration', 'Banking & Financial Services', 'Technology & Telecom', 'Real Estate & Infrastructure'],
    topGlobalEmployers: [
      'Cyril Amarchand Mangaldas (CAM)',
      'AZB & Partners',
      'Khaitan & Co',
      'Trilegal',
      'Shardul Amarchand Mangaldas (SAM)',
      'Clifford Chance / Allen & Overy (Global)',
    ],
    primeWorkLocations: ['Mumbai', 'New Delhi / NCR', 'Bengaluru', 'London (UK)', 'Singapore'],
    homeVsAbroadOverview: 'Corporate law expertise in M&A/Arbitration translates well to financial centers like London, Singapore, and Dubai following foreign conversion exams.',
    freelanceOpportunities: 'Independent Legal Advisory, Arbitration Claims Management, Contract Drafting Specialist.',
    startingSalaryRange: '₹12.0 - ₹20.0 Lakhs Per Annum (Tier-1 NLU -> Tier-1 Law Firm)',
    averageSalary: '₹25.0 - ₹45.0 Lakhs Per Annum (Mid-Level Associate)',
    experiencedSalary: '₹60.0 - ₹1.2 Crores Per Annum (Senior Partner / In-House GC)',
    highestPotentialEarnings: '₹3.0 - ₹10.0+ Crores Per Annum (Equity Partner / Senior Advocate Supreme Court)',
    govtSalaryScale: '₹10.0 - ₹18.0 LPA (Judicial Officer starting scale with official perks/housing)',
    privateSectorSalary: '₹12.0 - ₹80.0+ LPA',
    selfEmploymentEarnings: '₹5.0 LPA (Initial Independent Practice) to Unlimited (Top Litigators charge ₹5-25 Lakhs per appearance)',
    salaryByExperience: [
      { stage: 'Entry-Level (0-2 yrs)', range: '₹12 - ₹18 LPA (Tier-1 Firm)' },
      { stage: 'Mid-Career (3-6 yrs)', range: '₹22 - ₹40 LPA' },
      { stage: 'Senior (7-10 yrs)', range: '₹50 - ₹90 LPA' },
      { stage: 'Principal / Executive (10+ yrs)', range: '₹1.5 - ₹5.0+ Crores' },
    ],
    salaryBySpecialization: [
      { specialization: 'Corporate M&A & Private Equity', avgSalary: '₹28 LPA' },
      { specialization: 'Intellectual Property & Cyber Law', avgSalary: '₹20 LPA' },
      { specialization: 'Commercial Arbitration', avgSalary: '₹24 LPA' },
      { specialization: 'General Trial Litigation', avgSalary: '₹12 LPA' },
    ],
    keySalaryFactors: [
      'Graduating College Tier (Tier-1 NLUs vs State Colleges)',
      'Corporate Law Firm vs Independent Court Practice',
      'Specialization in M&A, Banking, or Cross-Border Disputes',
    ],
    topCountriesAbroad: ['United Kingdom', 'Singapore', 'United States', 'United Arab Emirates (Dubai)'],
    requiredExamsAbroad: ['Solicitors Qualifying Examination (SQE) - UK', 'New York State Bar Exam - USA', 'QFTT - Singapore'],
    licensingAbroad: 'Completion of SQE (UK) or LL.M. + NY Bar Exam (USA) allows Indian law graduates to practice globally as foreign legal consultants or solicitors.',
    educationEquivalency: 'Indian 5-year B.A. LL.B. degree recognized by the Bar Standards Board (UK) and American Bar Association (ABA) for post-graduate master studies.',
    salaryAbroadComparison: [
      { country: 'United Kingdom (London)', avgSalary: '£100,000 - £150,000', visaEase: 'High' },
      { country: 'United States (New York)', avgSalary: '$215,000 USD (BigLaw scale)', visaEase: 'Moderate' },
      { country: 'Singapore', avgSalary: '$140,000 SGD', visaEase: 'High' },
      { country: 'UAE (Dubai)', avgSalary: '$130,000 USD (Tax Free)', visaEase: 'Very High' },
    ],
    immigrationRelocationPath: 'Complete LL.M. in UK/USA -> Qualify SQE/NY Bar -> Direct sponsorship at Magic Circle or US international law firms.',
    advantages: [
      'High Earning Potential at Tier-1 Law Firms',
      'Intellectual Prestige and Societal Influence',
      'Recession-Resilient Demand (M&A prospers in booms, Litigation in downturns)',
    ],
    disadvantages: [
      'Extremely Long Working Hours (12-15 hour billable work days at top law firms)',
      'High Stress and Aggressive Delivery Timelines',
      'Initial Grind and Low Earnings in Early Independent Litigation',
    ],
    keyChallenges: [
      'Managing massive volume of documentation and complex statutory compliance changes',
      'Maintaining client confidentiality while operating under intense pressure',
    ],
    workLifeBalanceRating: 4,
    typicalWorkingHours: '60 - 75 Hours / Week',
    stressLevel: 'High / High-Stakes Financial & Legal Liability',
    jobSecurityRating: 9,
    competitionLevel: 'Extremely Fierce for Tier-1 Law Firms and Supreme Court Chambers',
    careerGrowthVelocity: 'Moderate to High based on billing track record and client acquisition',
    futureDemandOutlook: 'Growing rapidly at 7%+ CAGR with the expansion of India\'s commercial market, cross-border investments, and legal tech integration.',
    aiAutomationImpact: 'Drafting routine contracts and discovery research is being automated by Legal AI tools, shifting human legal focus to strategy, court advocacy, and complex negotiation.',
    aiReplacementRiskLevel: 'Low Risk (10-15%). Human advocacy, moral reasoning, and courtroom negotiations cannot be replaced by AI.',
    emergingOpportunities: [
      'Cross-Border Digital Asset & Cryptocurrency Regulation',
      'ESG (Environmental, Social, & Governance) Corporate Compliance',
      'AI Ethics & Algorithmic Liability Dispute Management',
    ],
    emergingSpecializations: [
      'Data Privacy & Cyber Law Specialist',
      'International Energy Transition Arbitrator',
      'Biotech & Patent Litigation Expert',
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // ==========================================
  // PROFILE 2: GENERAL SURGEON / SPECIALIST DOCTOR (India Home -> USMLE/PLAB Pathway)
  // ==========================================
  {
    id: 'report_clx_98471205',
    intakeId: 'intake_clx_0019285',
    careerName: 'General Surgeon & Specialist Medical Practitioner',
    careerOverview: `A Surgeon/Doctor in India undergoes extensive medical training to diagnose, treat, and perform surgical operations for acute and chronic conditions. After completing MBBS, doctors specialize through Master of Surgery (MS) or Diplomate of National Board (DNB) programs, and further super-specialize with M.Ch degrees in fields like Cardiothoracic, Neurosurgery, or Surgical Oncology.`,
    whatProfessionalDoes: `• Perform elective and emergency surgical procedures (laparoscopic, open, trauma management).
• Conduct clinical ward rounds, examine patients, and manage pre-operative and post-operative intensive care (ICU).
• Interpret diagnostic scans (CT, MRI, Pathology) to formulate clinical surgical interventions.
• Supervise junior residents, intern doctors, and clinical nursing teams during surgical emergencies.`,
    whyChooseThisCareer: `Offers maximum societal respect, absolute job security, and deep personal fulfillment through saving human lives. Medical doctors are non-replaceable and command lifelong prestige.`,
    whoIsSuitableFor: `Individuals with exceptional physical stamina, high emotional resilience, calm composure under life-or-death emergencies, steady hand dexterity, and commitment to lifelong clinical learning.`,
    requiredSkills: [
      'Surgical Dexterity & Precision Operative Control',
      'Emergency Resuscitation & Critical Care Management',
      'Differential Diagnosis & Clinical Judgment',
      'Patient Communication & Compassionate Care',
      'Biomedical & Anatomical Expertise',
    ],
    importantSubjects: [
      'Human Anatomy & Physiology',
      'Pathology & Microbiology',
      'Pharmacology',
      'General Surgery & Traumatology',
    ],
    workEnvironmentDesc: 'Government Tertiary Hospitals (AIIMS/PGIMER), Private Multi-specialty Hospitals (Apollo/Fortis), or Private Surgical Clinics.',
    typicalDayLife: `• 07:30 AM: Morning ward rounds in Post-Operative Surgical Ward & ICU.
• 09:00 AM: Major OT (Operation Theatre) list begins: perform laparoscopic cholecystectomies and hernia repairs.
• 02:30 PM: Outpatient Department (OPD) patient consultation and pre-op evaluations.
• 06:00 PM: Evening emergency call review and trauma patient stabilization.`,
    class10Requirements: 'Minimum 60%+ aggregate score with Science and Mathematics.',
    class11_12Stream: 'Medical Science Track: Physics, Chemistry, Biology/Biotechnology (PCB) + English.',
    subjectsRequired: ['Biology (Botany & Zoology)', 'Chemistry', 'Physics', 'English'],
    minQualification: 'DOCTORATE_PHD',
    ageLimit: 'Minimum 17 years completed by December 31 of admission year. No upper age limit for NEET UG / PG.',
    nationalityEligibility: 'Indian Citizens, NRIs, OCIs, PIOs, and Foreign Nationals.',
    medicalRequirements: 'Must meet clinical physical fitness standards for hospital duties and color vision checks.',
    courseOptions: [
      'MBBS (Bachelor of Medicine and Bachelor of Surgery) - 5.5 Years',
      'MS (Master of Surgery) / MD - 3 Years',
      'M.Ch (Magister Chirurgiae) Super-Specialization - 3 Years',
    ],
    courseDuration: '5.5 Years (MBBS including 1-yr Rotating Internship) + 3 Years (MS/MD Residency)',
    degreeRequired: 'MBBS degree recognized by the National Medical Commission (NMC)',
    entranceExams: ['NEET UG (Undergraduate Entry)', 'NEET PG / NExT (Postgraduate MS/MD Entry)', 'INI-CET (AIIMS/PGIMER/JIPMER)'],
    nationalExams: ['NEET UG', 'NEET PG / NExT', 'INI-CET'],
    stateExams: ['State Level NEET Medical Counseling Seats'],
    universityExams: ['AIIMS New Delhi Entrance (Now merged under NEET UG and INI-CET)'],
    examEligibility: 'Class 12 PCB aggregate 50% minimum (40% for SC/ST/OBC) and qualifying percentile in NEET UG.',
    examPattern: 'NEET UG: 180 MCQs out of 200 in 3 Hours 20 Minutes testing Biology (90), Chemistry (45), Physics (45).',
    examSubjects: ['Biology (Zoology & Botany)', 'Chemistry (Organic, Inorganic, Physical)', 'Physics'],
    numberOfQuestions: 180,
    markingScheme: '+4 marks for correct answer, -1 mark penalty for wrong response',
    examFrequency: 'Once Annually (May for NEET UG; INI-CET held twice yearly in May and November)',
    applicationProcess: 'Online submission on NTA NEET portal, generating roll number, appearing for exam, and registering for MCC national/state counseling.',
    applicationFees: '₹1,700 General; ₹1,600 EWS/OBC-NCL; ₹1,000 SC/ST/PwD',
    importantDates: 'NEET UG Registration: Feb-March; Exam: May First Sunday; Counseling: July-September.',
    prepStrategy: 'Memorize 100% of NCERT Biology word-for-word. Solve 20 years of past NEET/AIPMT physics and chemistry numerical problems.',
    recommendedBooks: [
      'NCERT Biology Textbooks Class 11 & 12',
      'Objective Physics by DC Pandey',
      'OP Tandon Physical & Organic Chemistry',
      'Bailey & Love\'s Short Practice of Surgery (Post-MBBS)',
    ],
    prepTimeline: '24 Months (Classes 11 & 12 dedicated preparation).',
    admissionProcess: 'Centralised Medical Counseling Committee (MCC) seat allotment based strictly on All India Rank (AIR) in NEET UG.',
    counsellingProcess: '4 Rounds of online Counseling (Round 1, Round 2, Mop-Up Round, Stray Vacancy Round).',
    quotaReservations: '15% All India Quota (AIQ), 85% State Domicile Quota, SC (15%), ST (7.5%), OBC-NCL (27%), EWS (10%), PwD (5%).',
    topGovtColleges: [
      'All India Institute of Medical Sciences (AIIMS), New Delhi',
      'Post Graduate Institute of Medical Education and Research (PGIMER), Chandigarh',
      'King George\'s Medical University (KGMU), Lucknow',
      'Maulana Azad Medical College (MAMC), New Delhi',
      'JIPMER, Puducherry',
    ],
    topPrivateColleges: [
      'Christian Medical College (CMC), Vellore',
      'Kasturba Medical College (KMC), Manipal',
      'St. John\'s Medical College, Bengaluru',
    ],
    collegeSelectionGuide: 'Target premier government medical colleges (AIIMS, MAMC) for maximum clinical patient exposure, subsidised tuition, and guaranteed stipend during PG residency.',
    expectedCutoffs: 'NEET Score 680+/720 for top AIIMS New Delhi / MAMC (General Category AIR under 1,000).',
    feeStructure: 'Govt Medical Colleges: ₹5,000 - ₹50,000 total course fee | Private Colleges: ₹15 Lakhs - ₹25 Lakhs / Year',
    availableScholarships: [
      'Central Sector Scheme of Scholarship for College and University Students',
      'ICMR Junior Research Fellowships',
      'State Government Medhavi Chhatra Yojana',
    ],
    stepByStepRoadmap: `Step 1: Secure high rank in NEET UG and gain admission to MBBS.
Step 2: Complete 4.5 years of academic study + 1 year compulsory rotating internship.
Step 3: Register with National Medical Commission (NMC) / State Medical Council.
Step 4: Crack NEET PG / INI-CET to secure MS (General Surgery) residency seat.
Step 5: Complete 3-year MS Surgery residency (work as Junior Resident Doctor).
Step 6: Optional M.Ch Super-Specialization (Neurosurgery/Cardiothoracic) OR Senior Residency in Hospital.`,
    internshipRequirements: 'Mandatory 12-month Compulsory Rotatory Residential Internship (CRRI) covering Surgery, Medicine, OB-GYN, Pediatrics, and Community Health.',
    licensingRegistration: 'Permanent Medical Registration Certificate issued by National Medical Commission (NMC) or State Medical Council.',
    entryLevelRoles: ['Junior Resident Doctor (MS Trainee)', 'Medical Officer (Primary Health Center)', 'Casualty Medical Officer'],
    midLevelRoles: ['Senior Resident Doctor (Surgery)', 'Assistant Professor (Govt Medical College)', 'Consultant Surgeon (Private Hospital)'],
    seniorLevelRoles: ['Chief General Surgeon', 'Head of Department (HOD Surgery)', 'Director of Surgical Services / Hospital Partner'],
    specializations: ['General & Laparoscopic Surgery', 'Orthopedic Surgery', 'Ophthalmology', 'ENT Surgery'],
    superSpecializations: ['Neurosurgery', 'Cardiothoracic & Vascular Surgery (CTVS)', 'Surgical Oncology', 'Urology', 'Pediatric Surgery'],
    higherEducationPaths: ['M.Ch (Super Specialization)', 'Fellowship of Royal College of Surgeons (FRCS - UK)', 'DNB Super-Specialty'],
    alternativeCareerPaths: ['Hospital Administration (MD/MBA)', 'Medical Research / Clinical Trials Lead', 'HealthTech Surgical Robotics Advisor'],
    govtJobOpportunities: 'Central Health Services (CHS), AIIMS Faculties, Indian Railway Medical Services, Armed Forces Medical Services (AFMC/Short Commission).',
    privateJobOpportunities: 'Corporate Hospitals (Apollo, Fortis, Max, Manipal), Specialty Surgical Clinics, Diagnostic chains.',
    selfEmploymentOptions: 'Establishing a private Surgical Nursing Home, Polyclinic, or Day-Care Surgery Center.',
    hiringIndustries: ['Healthcare & Medical Diagnostics', 'Hospital Chains', 'Pharmaceutical & Surgical Robotics', 'Medical Academics'],
    topGlobalEmployers: [
      'AIIMS / Central Government Hospitals',
      'Apollo Hospitals Group',
      'Fortis Healthcare',
      'Max Healthcare',
      'NHS (National Health Service - UK)',
      'US Hospital Systems (Post USMLE Residency)',
    ],
    primeWorkLocations: ['New Delhi', 'Mumbai', 'Bengaluru', 'Chennai', 'London (UK)', 'Chicago/New York (USA)'],
    homeVsAbroadOverview: 'High domestic demand across tier-1 and tier-2 Indian cities. Medical degrees require overseas licensing exams (USMLE for USA, PLAB/GMC for UK, AMC for Australia).',
    freelanceOpportunities: 'Visiting Consultant Surgeon across multiple private hospitals and surgical centers.',
    startingSalaryRange: '₹8.0 - ₹15.0 Lakhs Per Annum (Fresh Post-MBBS / Junior Resident)',
    averageSalary: '₹18.0 - ₹35.0 Lakhs Per Annum (MS Surgery Specialist / Senior Resident)',
    experiencedSalary: '₹40.0 - ₹90.0 Lakhs Per Annum (Senior Surgical Consultant)',
    highestPotentialEarnings: '₹1.5 - ₹5.0+ Crores Per Annum (Top Super-Specialist Surgeon / Surgical Oncology Leader)',
    govtSalaryScale: '₹12.0 - ₹24.0 LPA (Govt Pay Matrix Level 10 to Level 14 + Non-Practicing Allowance NPA)',
    privateSectorSalary: '₹18.0 - ₹1.2+ Crores LPA',
    selfEmploymentEarnings: '₹20.0 LPA to Unlimited (Based on private clinic surgical volume)',
    salaryByExperience: [
      { stage: 'Entry-Level (0-2 yrs)', range: '₹8 - ₹14 LPA (Resident Stipend)' },
      { stage: 'Mid-Career (3-6 yrs)', range: '₹18 - ₹32 LPA (Consultant)' },
      { stage: 'Senior (7-10 yrs)', range: '₹40 - ₹80 LPA' },
      { stage: 'Principal / Executive (10+ yrs)', range: '₹1.0 - ₹3.5+ Crores' },
    ],
    salaryBySpecialization: [
      { specialization: 'Neurosurgery / CTVS (Super Specialty)', avgSalary: '₹55 LPA' },
      { specialization: 'Surgical Oncology', avgSalary: '₹48 LPA' },
      { specialization: 'General Laparoscopic Surgery', avgSalary: '₹28 LPA' },
      { specialization: 'Orthopedic Surgery', avgSalary: '₹32 LPA' },
    ],
    keySalaryFactors: [
      'Super-specialization degrees (M.Ch vs MS)',
      'Surgical volume and success rate of complex operations',
      'Metro city corporate hospital location vs Govt hospital pay scale',
    ],
    topCountriesAbroad: ['United States', 'United Kingdom', 'Australia', 'United Arab Emirates (Dubai / Abu Dhabi)', 'Canada'],
    requiredExamsAbroad: [
      'USMLE Step 1, Step 2 CK, Step 3 (USA)',
      'PLAB 1 & 2 / UKMLA (United Kingdom)',
      'AMC Exam (Australia)',
    ],
    licensingAbroad: 'Passing USMLE + ECFMG Certification allows entry into US residency match. Passing PLAB + IELTS/OET enables GMC registration in the UK.',
    educationEquivalency: 'NMC-recognized Indian MBBS degree is WHO/FAIMER directory listed, making graduates eligible for foreign medical registration.',
    salaryAbroadComparison: [
      { country: 'United States', avgSalary: '$380,000 - $550,000 USD (General/Orthopedic Surgeon)', visaEase: 'Moderate' },
      { country: 'United Kingdom', avgSalary: '£90,000 - £130,000 GBP (NHS Consultant)', visaEase: 'High' },
      { country: 'Australia', avgSalary: '$300,000 - $450,000 AUD', visaEase: 'Moderate' },
      { country: 'UAE (Dubai)', avgSalary: '$200,000 - $320,000 USD (Tax Free)', visaEase: 'High' },
    ],
    immigrationRelocationPath: 'Clear USMLE Step 1 & 2 CK -> Clinical Electives in USA -> Match into General Surgery Residency (J-1/H-1B Visa) -> Board Certification.',
    advantages: [
      'Maximum Prestige and Lifetime Social Respect',
      'Absolute Career Security (Zero risk of unemployment or economic obsolescence)',
      'Deep Fulfillment from Lifesaving Clinical Interventions',
    ],
    disadvantages: [
      'Extremely Long Education Path (10-12 years before reaching full independence)',
      'Physical Exhaustion, Night Duties, and Severe Emergency Sleep Deprivation',
      'High Psychological Burden and Medicolegal Risk',
    ],
    keyChallenges: [
      'Managing critical patient complications and intense family emotional expectations',
      'Maintaining physical stamina during 6-8 hour operating theatre procedures',
    ],
    workLifeBalanceRating: 3,
    typicalWorkingHours: '65 - 80 Hours / Week (Including night call shifts)',
    stressLevel: 'Extremely High / High-Stakes Life Preservation',
    jobSecurityRating: 10,
    competitionLevel: 'Fierce for NEET UG / PG seats (Top 1% selection rate)',
    careerGrowthVelocity: 'Steady, non-linear growth peaking in 40s and 50s',
    futureDemandOutlook: 'Unbounded Growth. Expanding aging populations and surgical chronic diseases guarantee rising demand for specialized surgeons through 2050.',
    aiAutomationImpact: 'Robotic Surgery (Da Vinci Systems) acts as a force multiplier for surgeons. AI enhances diagnostic imaging precision, but execution remains 100% human-controlled.',
    aiReplacementRiskLevel: 'Zero Risk (0%). Physical surgical dexterity, dynamic operative decision-making, and patient empathy cannot be automated.',
    emergingOpportunities: [
      'AI-Guided Micro-Robotic Minimally Invasive Surgery',
      '3D-Printed Anatomical Implants & Organ Reconstruction',
      'Telesurgery (Remote Long-Distance Robotic Operations)',
    ],
    emergingSpecializations: [
      'Robotic Surgical Oncologist',
      'Fetal and Neonatal Surgeon',
      'Transplant Surgery Specialist',
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // ==========================================
  // PROFILE 3: FULL-STACK SOFTWARE & SYSTEMS ENGINEER (India Home -> Silicon Valley / Global Remote)
  // ==========================================
  {
    id: 'report_clx_98471206',
    intakeId: 'intake_clx_0019286',
    careerName: 'Full-Stack Software & Distributed Systems Engineer',
    careerOverview: `A Full-Stack & Systems Engineer designs, builds, and maintains high-performance software applications, web architectures, backend microservices, and databases. In India's flourishing tech sector, software engineers scale platforms that serve hundreds of millions of users, transitioning from core programming to system architecture and distributed cloud infrastructure.`,
    whatProfessionalDoes: `• Develop production-grade backend APIs and microservices using modern languages (Node.js, Go, Python, Java).
• Build modern responsive web application frontends (React, Next.js, TypeScript, Tailwind CSS).
• Design scalable relational (PostgreSQL) and NoSQL (MongoDB, Redis) database architectures.
• Configure Docker containerization, CI/CD automated deployment pipelines, and cloud instances (AWS/GCP).`,
    whyChooseThisCareer: `Fastest pathway to high wealth creation, early career autonomy, global mobility, and remote work options. Software engineering offers immediate meritocratic growth without long qualification delays.`,
    whoIsSuitableFor: `Logical problem solvers, self-taught fast learners, and technology enthusiasts who enjoy translating abstract real-world problems into clean, optimized code.`,
    requiredSkills: [
      'Full-Stack Web Development (React, Next.js, Node.js)',
      'Data Structures & Algorithms (LeetCode / Codeforces)',
      'Relational & NoSQL Database Design (PostgreSQL, MongoDB)',
      'System Architecture & Microservices Design',
      'Docker, Kubernetes, & AWS Cloud Deployment',
    ],
    importantSubjects: [
      'Data Structures & Algorithms',
      'Database Management Systems (DBMS)',
      'Operating Systems & Networking',
      'Object-Oriented Programming (OOP)',
    ],
    workEnvironmentDesc: 'Modern tech corporate campuses, hyper-growth startup hubs, or 100% remote work-from-anywhere setups.',
    typicalDayLife: `• 09:30 AM: Morning engineering stand-up sync on sprint progress.
• 10:15 AM: Code review and pull-request verification for peer developers.
• 11:30 AM: Core Coding Focus: Implement asynchronous webhook processor and PostgreSQL database migration.
• 04:00 PM: System design review for high-concurrency payment gateway integration.`,
    class10Requirements: 'Minimum 60%+ aggregate score with strong performance in Mathematics.',
    class11_12Stream: 'Science Stream with Physics, Chemistry, and Advanced Mathematics (PCM).',
    subjectsRequired: ['Mathematics', 'Physics', 'Chemistry', 'Computer Science / IP (Optional)'],
    minQualification: 'BACHELORS',
    ageLimit: 'No age restrictions for industry hiring. University entrance exams (JEE) have age/attempt limits.',
    nationalityEligibility: 'Open globally.',
    medicalRequirements: 'Standard ergonomic office clearance; no special medical checks.',
    courseOptions: [
      'B.Tech / B.E. in Computer Science Engineering (CSE) / IT',
      'B.C.A. (Bachelor of Computer Applications) + M.C.A.',
      'B.Sc in Computer Science / Data Science',
    ],
    courseDuration: '4 Years (B.Tech / B.E.) OR 3 Years (BCA / B.Sc)',
    degreeRequired: 'B.Tech / B.E. / B.Sc / BCA in Computer Science or related quantitative technical domain',
    entranceExams: ['JEE Main (National)', 'JEE Advanced (IITs)', 'BITSAT (BITS Pilani)', 'VITEEE', 'MET', 'MHT-CET'],
    nationalExams: ['JEE Main', 'JEE Advanced'],
    stateExams: ['MHT CET (Maharashtra)', 'KCET (Karnataka)', 'WBJEE (West Bengal)', 'TNEA (Tamil Nadu)'],
    universityExams: ['BITSAT (BITS Pilani)', 'VITEEE (VIT Vellore)', 'SRMJEEE'],
    examEligibility: 'Class 12 PCM pass with minimum 75% aggregate score for IITs/NITs/BITSAT (60% for state/private universities).',
    examPattern: 'Computer-Based Test (CBT): 90 Questions testing Physics, Chemistry, and Mathematics over 3 Hours.',
    examSubjects: ['Mathematics (Algebra, Calculus, Coordinate Geometry)', 'Physics', 'Chemistry'],
    numberOfQuestions: 75,
    markingScheme: '+4 marks for correct response, -1 mark penalty for incorrect response',
    examFrequency: 'Twice Annually (JEE Main Session 1 in Jan, Session 2 in April)',
    applicationProcess: 'Online registration on NTA portal, exam center selection, score release, and JOSAA / CSAB centralized counseling allotment.',
    applicationFees: '₹1,000 for General Male; ₹800 for Female / Reserved categories',
    importantDates: 'November-December (JEE Main Reg); January & April (Exam Cycles); June-July (JoSAA Counseling).',
    prepStrategy: 'Focus on speed and accuracy in Mathematics and Physics. Solve 10 years of JEE Main / Advanced past paper questions and build personal coding projects on GitHub.',
    recommendedBooks: [
      'Problems in General Physics by IE Irodov',
      'Advanced Problems in Mathematics by Vikas Gupta',
      'Cracking the Coding Interview by Gayle Laakmann McDowell',
      'Data Structures and Algorithms Made Easy by Narasimha Karumanchi',
    ],
    prepTimeline: '24 Months (Classes 11 & 12).',
    admissionProcess: 'JoSAA / CSAB online counseling based on All India Ranks in JEE Main (for NITs/IIITs) and JEE Advanced (for IITs).',
    counsellingProcess: '6 Rounds of centralized JoSAA online choice filling and seat locking.',
    quotaReservations: 'SC (15%), ST (7.5%), OBC-NCL (27%), EWS (10%), Female Supernumerary (20%), Home State Quota in NITs.',
    topGovtColleges: [
      'Indian Institute of Technology (IIT) Bombay, Delhi, Madras, Kanpur, Kharagpur',
      'National Institute of Technology (NIT) Trichy, Surathkal, Warangal',
      'Indian Institute of Information Technology (IIIT) Hyderabad, Allahabad, Bangalore',
    ],
    topPrivateColleges: [
      'BITS Pilani (Pilani, Goa, Hyderabad Campuses)',
      'Vellore Institute of Technology (VIT), Vellore',
      'Thapar Institute of Engineering and Technology, Patiala',
    ],
    collegeSelectionGuide: 'Target IITs, IIIT Hyderabad/Bangalore, and BITS Pilani for highest Tier-1 global placement offers ($100k+ USD international / ₹30L+ domestic).',
    expectedCutoffs: 'JEE Main Percentile > 99.5 for CS in top NITs; JEE Advanced Rank under 1,000 for CS in top 7 IITs.',
    feeStructure: 'IITs/NITs: ₹8 Lakhs - ₹10 Lakhs total 4-year fee | Private (BITS/VIT): ₹15 Lakhs - ₹25 Lakhs total fee',
    availableScholarships: [
      'Reliance Foundation Undergraduate Scholarships in STEM',
      'MHRD Merit-cum-Means Fee Waivers (100% tuition waiver for EWS in IITs)',
      'KVPY / INSPIRE Fellowships',
    ],
    stepByStepRoadmap: `Step 1: Complete High School with high score in PCM and JEE Main/Advanced.
Step 2: Graduate with B.Tech in Computer Science; maintain strong data structures (LeetCode) profile.
Step 3: Win summer engineering internships in 3rd year at product-based software companies.
Step 4: Receive PPO (Pre-Placement Offer) or crack campus placement as Software Development Engineer I (SDE-1).
Step 5: Transition to SDE-2 (3-5 Yrs) taking ownership of critical backend system modules.
Step 6: Elevate to Senior SDE / Staff Software Engineer / Engineering Manager (6+ Yrs).`,
    internshipRequirements: 'One mandatory 8-12 week software engineering internship at product company or high-growth startup.',
    licensingRegistration: 'No government license required. Industry certifications (AWS Certified Developer, CKA Kubernetes) add candidate value.',
    entryLevelRoles: ['Software Development Engineer I (SDE-1)', 'Frontend Engineer', 'Backend Developer', 'QA Automation Engineer'],
    midLevelRoles: ['Software Development Engineer II (SDE-2)', 'Full-Stack Developer', 'DevOps / Cloud Specialist'],
    seniorLevelRoles: ['Senior Software Engineer', 'Staff Engineer', 'Engineering Manager', 'Chief Technology Officer (CTO)'],
    specializations: ['Full-Stack Web Architectures', 'Distributed Microservices & Cloud Native', 'Mobile Application Development (iOS/Android)', 'DevOps & SRE Engineering'],
    superSpecializations: ['High-Frequency Trading Infrastructure', 'Compiler & Runtime Engine Development', 'Distributed Ledger Engine Architecture'],
    higherEducationPaths: ['M.S. in Computer Science in USA/Germany', 'M.Tech at IITs (via GATE Exam)', 'MBA at IIMs'],
    alternativeCareerPaths: ['Product Manager (PM)', 'Data Scientist / AI Engineer', 'Technical Founder / SaaS Entrepreneur'],
    govtJobOpportunities: 'NIC (National Informatics Centre), ISRO Scientist/Engineer-SC, BARC, DRDO, Public Sector Banks (IT Officer).',
    privateJobOpportunities: 'Product MNCs (FAANG / MAMAA), FinTech Startups, Unicorn SaaS Companies, Global In-house Centers (GICs).',
    selfEmploymentOptions: 'Freelance Software Contracting, Launching Independent SaaS Products, Technical Consulting.',
    hiringIndustries: ['Internet & Software Services', 'Fintech & Digital Banking', 'E-Commerce & Logistics', 'HealthTech & EdTech'],
    topGlobalEmployers: [
      'Google / Alphabet',
      'Microsoft',
      'Amazon',
      'Meta',
      'Atlassian',
      'Uber',
      'Flipkart / PhonePe',
    ],
    primeWorkLocations: ['Bengaluru', 'Hyderabad', 'Pune', 'Gurugram / NCR', 'Seattle / San Francisco (USA)', 'London (UK)'],
    homeVsAbroadOverview: 'India has world-class domestic engineering opportunities (Bengaluru/Hyderabad). Overseas transition to USA, Europe, or Singapore is straightforward via internal company transfers (L-1 visa) or MS degrees.',
    freelanceOpportunities: 'High-value remote contracting via platforms (Toptal, Turing, Arc) or direct agency client retainers ($50 - $120 / hr).',
    startingSalaryRange: '₹8.0 - ₹22.0 Lakhs Per Annum (Tier-1 College SDE-1 Fresh Graduate)',
    averageSalary: '₹22.0 - ₹40.0 Lakhs Per Annum (SDE-2 with 3-5 years experience)',
    experiencedSalary: '₹45.0 - ₹90.0 Lakhs Per Annum (Senior SDE / Staff Engineer)',
    highestPotentialEarnings: '₹1.5 - ₹4.0+ Crores Per Annum (Principal Engineer / VP Engineering with Stock Options)',
    govtSalaryScale: '₹8.0 - ₹14.0 LPA (Scientist-SC scale + Central Govt benefits)',
    privateSectorSalary: '₹10.0 - ₹1.5+ Crores LPA',
    selfEmploymentEarnings: '₹15.0 LPA to Unlimited (SaaS revenues / consulting)',
    salaryByExperience: [
      { stage: 'Entry-Level (0-2 yrs)', range: '₹10 - ₹24 LPA (Tier-1 Product Company)' },
      { stage: 'Mid-Career (3-6 yrs)', range: '₹25 - ₹45 LPA' },
      { stage: 'Senior (7-10 yrs)', range: '₹50 - ₹95 LPA' },
      { stage: 'Principal / Executive (10+ yrs)', range: '₹1.2 - ₹3.5+ Crores' },
    ],
    salaryBySpecialization: [
      { specialization: 'Full-Stack Distributed Systems', avgSalary: '₹32 LPA' },
      { specialization: 'DevOps & Cloud SRE Architecture', avgSalary: '₹28 LPA' },
      { specialization: 'Mobile Application Engineering', avgSalary: '₹24 LPA' },
      { specialization: 'Frontend UI/UX Systems', avgSalary: '₹22 LPA' },
    ],
    keySalaryFactors: [
      'Product-Based Company vs IT Service Company (3-4x salary difference)',
      'Data Structures & Algorithm Problem-Solving Skill (LeetCode proficiency)',
      'Equity, Stock Grants (RSUs), and Joining Bonuses',
    ],
    topCountriesAbroad: ['United States', 'Germany', 'United Kingdom', 'Canada', 'Singapore', 'Netherlands'],
    requiredExamsAbroad: ['GRE (For Master\'s Program Entry)', 'TOEFL / IELTS', 'Direct Technical Code Pairing Interviews'],
    licensingAbroad: 'No state licensing required. Global tech industry relies entirely on technical coding performance and system design interviews.',
    educationEquivalency: 'Indian 4-year B.Tech degree recognized under Washington Accord across USA, UK, Canada, Australia, and Europe.',
    salaryAbroadComparison: [
      { country: 'United States (Silicon Valley)', avgSalary: '$160,000 - $250,000 USD', visaEase: 'Moderate' },
      { country: 'Germany (Berlin/Munich)', avgSalary: '€75,000 - €110,000 EUR', visaEase: 'Very High' },
      { country: 'United Kingdom (London)', avgSalary: '£80,000 - £130,000 GBP', visaEase: 'High' },
      { country: 'Singapore', avgSalary: '$120,000 - $180,000 SGD', visaEase: 'High' },
    ],
    immigrationRelocationPath: 'Secure employment at US/EU tech MNC in India -> Qualify for L-1 Intra-Company Transfer OR pursue MS in US/Germany -> Post-Study Work Permit -> H-1B / EU Blue Card.',
    advantages: [
      'Exceptional Pay Tiers relative to years of experience',
      'Flexibility for Remote Work and Geographic Autonomy',
      'Meritocratic Hiring focused on problem-solving ability',
    ],
    disadvantages: [
      'Screen fatigue and physical sedentary strain',
      'Need for constant re-skilling as frameworks change rapidly',
      'High competition for entry-level positions',
    ],
    keyChallenges: [
      'Keeping pace with AI coding assistants and mastering complex microservice edge cases',
      'Managing high-concurrency production system incidents and downtime pressure',
    ],
    workLifeBalanceRating: 7,
    typicalWorkingHours: '40 - 50 Hours / Week',
    stressLevel: 'Moderate / High during production deployments or release cycles',
    jobSecurityRating: 8,
    competitionLevel: 'Fierce for freshers at Tier-1 product companies; High demand for experienced engineers',
    careerGrowthVelocity: 'Very Rapid (Promotions every 1.5 to 3 years)',
    futureDemandOutlook: 'Robust Expansion. Software systems remain the backbone of every modern industry, with digital transformation driving continuous hiring through 2040.',
    aiAutomationImpact: 'AI code generators increase developer productivity. Engineers transition from typing boilerplate code to designing complex system architectures and verifying logic.',
    aiReplacementRiskLevel: 'Low Risk (15%). System design, complex edge-case handling, business logic formulation, and human user empathy cannot be automated.',
    emergingOpportunities: [
      'AI-Native Application Engineering (LLM Wrapper Architectures)',
      'Edge & Embedded Systems Integration',
      'Zero-Trust Cloud Security Software',
    ],
    emergingSpecializations: [
      'AI Systems Engineer',
      'Cloud Native Infrastructure Developer',
      'WebAssembly & High-Performance Web Engineer',
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // ==========================================
  // PROFILE 4: ELECTRICAL & ELECTRONICS ENGINEER (India Home -> Core PSUs & Semiconductor Industry)
  // ==========================================
  {
    id: 'report_clx_98471207',
    intakeId: 'intake_clx_0019287',
    careerName: 'Electrical & Electronics Systems Engineer',
    careerOverview: `An Electrical Engineer in India designs, develops, tests, and oversees the manufacturing of electrical equipment, power distribution systems, electric vehicle (EV) powertrains, smart grids, microprocessors, and embedded hardware. Electrical engineers are critical to India's national power grid, clean energy transition, and booming semiconductor manufacturing ecosystem.`,
    whatProfessionalDoes: `• Design electric power distribution networks, transformers, circuit breakers, and industrial control systems.
• Develop embedded firmware and microcontrollers for Electric Vehicles (EVs), robotics, and IoT hardware.
• Conduct load-flow analysis, fault calculations, and power quality assessments using MATLAB / ETAP.
• Test and validate VLSI semiconductor chips, printed circuit boards (PCBs), and power electronics converters.`,
    whyChooseThisCareer: `Offers access to core Public Sector Undertaking (PSU) government jobs with lifetime security, as well as lucrative roles in the high-growth global semiconductor and Electric Vehicle (EV) industries.`,
    whoIsSuitableFor: `Individuals who enjoy physics, electromagnetism, circuit theory, hardware tinkering, and applying mathematical principles to physical power and electronics systems.`,
    requiredSkills: [
      'Circuit Analysis & Electromagnetic Field Theory',
      'Embedded C / C++ & Microcontrollers (ARM, STM32)',
      'Power Electronics & Motor Drive Control',
      'MATLAB, Simulink, & ETAP Simulation',
      'PCB Design & VLSI Cadence Design Tools',
    ],
    importantSubjects: [
      'Electrical Machines & Power Systems',
      'Control Systems & Signals',
      'Power Electronics & Analog Circuits',
      'Electromagnetic Theory',
    ],
    workEnvironmentDesc: 'Power plants, semiconductor fabrication cleanrooms, industrial manufacturing units, EV R&D centers, or corporate design offices.',
    typicalDayLife: `• 08:30 AM: Inspect high-voltage switchyard equipment and power transformer telemetry.
• 11:00 AM: Simulate DC-DC converter efficiency and thermal profiles in MATLAB / Simulink.
• 02:00 PM: Test micro-controller firmware on hardware bench for EV battery management system (BMS).
• 05:00 PM: Review electrical schematic layout and safety compliance with manufacturing engineers.`,
    class10Requirements: 'Minimum 60%+ in Mathematics and Science.',
    class11_12Stream: 'Science Stream with Physics, Chemistry, and Advanced Mathematics (PCM).',
    subjectsRequired: ['Physics', 'Mathematics', 'Chemistry', 'English'],
    minQualification: 'BACHELORS',
    ageLimit: 'No age limit for private industry; Govt/PSU recruitment via GATE typically caps age between 28-30 years for General category.',
    nationalityEligibility: 'Indian Citizens (mandatory for PSU recruiting via GATE) & Foreign Nationals for private sector.',
    medicalRequirements: 'Normal color vision is mandatory for electrical wiring and safety engineering compliance.',
    courseOptions: [
      'B.Tech / B.E. in Electrical Engineering (EE) / Electrical & Electronics Engineering (EEE)',
      'B.Tech in Electronics & Communication Engineering (ECE)',
      'M.Tech in Power Electronics / VLSI Design / Control Systems',
    ],
    courseDuration: '4 Years (B.Tech / B.E.) + Optional 2 Years (M.Tech)',
    degreeRequired: 'B.Tech / B.E. in Electrical or Electronics Engineering',
    entranceExams: ['JEE Main', 'JEE Advanced', 'GATE (Postgraduate / PSU Direct Recruitment)', 'BITSAT', 'State CETs'],
    nationalExams: ['JEE Main', 'JEE Advanced', 'GATE (Graduate Aptitude Test in Engineering)'],
    stateExams: ['MHT-CET', 'KCET', 'WBJEE', 'TNEA'],
    universityExams: ['BITSAT', 'VITEEE', 'SRMJEEE'],
    examEligibility: 'Class 12 PCM with minimum 75% aggregate for IITs/NITs (60% for state/private universities).',
    examPattern: 'JEE Main (CBT 3 Hrs, 90 MCQs/Numerical) | GATE Exam: 65 Questions (100 Marks, 3 Hours) testing EE core engineering.',
    examSubjects: ['Engineering Mathematics', 'Electric Circuits', 'Power Systems', 'Electrical Machines', 'Control Systems', 'Analog/Digital Electronics'],
    numberOfQuestions: 65,
    markingScheme: 'GATE: +1 or +2 marks for correct answer, -0.33 or -0.66 penalty for wrong MCQs (No penalty for Numerical Answer Type NAT).',
    examFrequency: 'JEE Main (Twice yearly); GATE (Once annually in February).',
    applicationProcess: 'Online application on GOAPS portal for GATE; scorecard utilized for direct PSU recruitment and M.Tech admissions.',
    applicationFees: 'GATE Fee: ₹1,800 General; ₹900 Female / SC / ST / PwD',
    importantDates: 'September-October (GATE Reg); February (GATE Exam); March (GATE Scorecard Release).',
    prepStrategy: 'Focus on core concepts in Electrical Machines, Power Systems, and Circuit Theory. Solve past 20 years GATE paper problems to build accuracy.',
    recommendedBooks: [
      'Electrical Machinery by PS Bimbhra',
      'Power System Engineering by Nagrath & Kothari',
      'Automatic Control Systems by BC Kuo',
      'Fundamentals of Electric Circuits by Alexander & Sadiku',
    ],
    prepTimeline: '12 to 24 Months.',
    admissionProcess: 'PSU direct interviews based on GATE Score; M.Tech seat allotment via CCMT (for NITs) and COAP (for IITs).',
    counsellingProcess: 'COAP (Common Offer Acceptance Portal) online rounds for IIT M.Tech seats.',
    quotaReservations: 'Standard Govt Reservations in PSUs and IITs: SC (15%), ST (7.5%), OBC-NCL (27%), EWS (10%), PwD (5%).',
    topGovtColleges: [
      'Indian Institute of Technology (IIT) Bombay, Madras, Kanpur, Kharagpur, Roorkee',
      'National Institute of Technology (NIT) Trichy, Surathkal, Warangal',
      'College of Engineering Pune (COEP) / VJTI Mumbai',
    ],
    topPrivateColleges: [
      'BITS Pilani (Pilani & Goa Campuses)',
      'Vellore Institute of Technology (VIT), Vellore',
      'PSG College of Technology, Coimbatore',
    ],
    collegeSelectionGuide: 'Choose top IITs/NITs for direct PSU recruitment visits (NTPC, PowerGrid, BHEL) and chip design semiconductor company placements (Texas Instruments, Qualcomm).',
    expectedCutoffs: 'GATE Marks > 75/100 for direct PSU recruitment call in General category (Rank under 300).',
    feeStructure: 'IITs/NITs: ₹8 Lakhs - ₹10 Lakhs total 4-year fee | PSUs offer direct starting salaries upon graduation.',
    availableScholarships: [
      'MHRD GATE Stipend (₹12,400/month during M.Tech)',
      'Central Sector Scheme for Engineering Students',
      'State AICTE Pragati & Saksham Scholarships',
    ],
    stepByStepRoadmap: `Step 1: Complete B.Tech in Electrical Engineering with high CGPA.
Step 2: Crack GATE Exam with All India Rank under 500.
Step 3: Secure direct Executive Trainee selection in Power PSUs (PowerGrid, NTPC, IOCL) OR join Semiconductor MNC.
Step 4: Gain field exposure in high-voltage grids, power electronics, or chip design (0-3 Years).
Step 5: Advance to Senior Manager / Lead Systems Engineer (4-8 Years).
Step 6: Become Chief Engineer / General Manager / Lead Hardware Architect (10+ Years).`,
    internshipRequirements: 'Mandatory 6-8 week industrial training in a power grid station, manufacturing plant, or electronics R&D lab.',
    licensingRegistration: 'Chartered Engineer (CEn) certification from Institution of Engineers India (IEI) valued for government project sign-offs.',
    entryLevelRoles: ['Executive Trainee (PSU)', 'Electrical Design Engineer', 'Embedded Hardware Engineer', 'Graduate Engineer Trainee (GET)'],
    midLevelRoles: ['Assistant Manager (Power Grid)', 'Senior Power Electronics Engineer', 'VLSI Physical Design Lead'],
    seniorLevelRoles: ['Chief Electrical Engineer', 'Plant Manager', 'Director of Hardware Engineering', 'General Manager (PSU)'],
    specializations: ['Power Electronics & EV Powertrains', 'VLSI & Microelectronics Design', 'Smart Grid & Renewable Energy Integration', 'Control Systems & Industrial Automation'],
    superSpecializations: ['Wide-Bandgap (SiC/GaN) Power Devices', 'Autonomous Vehicle Sensor Fusion Systems', 'High-Voltage Direct Current (HVDC) Transmission'],
    higherEducationPaths: ['M.Tech in Power Electronics / VLSI Design', 'MS in Electrical Engineering (USA/Germany)', 'MBA in Operations Management'],
    alternativeCareerPaths: ['Software Engineering / IT roles (High cross-over rate)', 'Management Consulting', 'Patents & IPR Attorney in Electronics'],
    govtJobOpportunities: 'PowerGrid (PGCIL), NTPC, BHEL, IOCL, ONGC, ISRO, DRDO, Indian Railways (IES / ESE Officer).',
    privateJobOpportunities: 'Semiconductor design MNCs, EV manufacturers (Tata Motors, Ather, Ola Electric), Industrial Automation (Siemens, ABB, Schneider Electric).',
    selfEmploymentOptions: 'Electrical Safety Audit Contracting, Renewable Energy / Solar Rooftop EPC Contracting, Custom Embedded Hardware Agency.',
    hiringIndustries: ['Electric Power & Renewable Energy', 'Semiconductors & Microelectronics', 'Electric Vehicles (EV) & Automotive', 'Industrial Automation & Heavy Machinery'],
    topGlobalEmployers: [
      'Power Grid Corporation of India (PGCIL)',
      'NTPC Limited',
      'Texas Instruments',
      'Qualcomm',
      'ABB Group',
      'Siemens',
      'Tata Motors (EV Division)',
    ],
    primeWorkLocations: ['Bengaluru', 'Hyderabad', 'Pune', 'New Delhi / NCR', 'Munich (Germany)', 'Austin/California (USA)'],
    homeVsAbroadOverview: 'Incredible domestic PSU job stability in India. Foreign transition to Germany and USA is highly lucrative in Semiconductor Design and EV Hardware.',
    freelanceOpportunities: 'Solar Power Plant System Design, Custom PCB Layout & Firmware Development Retainers.',
    startingSalaryRange: '₹10.0 - ₹18.0 Lakhs Per Annum (PSUs via GATE OR Top Chip Design MNCs)',
    averageSalary: '₹18.0 - ₹32.0 Lakhs Per Annum (Mid-Level EE Lead)',
    experiencedSalary: '₹35.0 - ₹70.0 Lakhs Per Annum (Senior Manager / Principal Hardware Architect)',
    highestPotentialEarnings: '₹1.0 - ₹2.5+ Crores Per Annum (Global Semiconductor VP / Executive Director)',
    govtSalaryScale: '₹12.0 - ₹22.0 LPA (PSU Executive Scale + Housing Allowance + Medical + Superannuation)',
    privateSectorSalary: '₹8.0 - ₹80.0+ LPA',
    selfEmploymentEarnings: '₹10.0 - ₹40.0 LPA (Electrical Contracting & Solar EPC)',
    salaryByExperience: [
      { stage: 'Entry-Level (0-2 yrs)', range: '₹10 - ₹16 LPA (PSU / Tier-1 Core)' },
      { stage: 'Mid-Career (3-6 yrs)', range: '₹18 - ₹28 LPA' },
      { stage: 'Senior (7-10 yrs)', range: '₹32 - ₹55 LPA' },
      { stage: 'Principal / Executive (10+ yrs)', range: '₹60 - ₹1.8+ Crores' },
    ],
    salaryBySpecialization: [
      { specialization: 'VLSI & Semiconductor Chip Design', avgSalary: '₹34 LPA' },
      { specialization: 'EV Power Electronics & BMS', avgSalary: '₹26 LPA' },
      { specialization: 'PSU Power Generation & Distribution', avgSalary: '₹20 LPA' },
      { specialization: 'Industrial Automation & Drives', avgSalary: '₹16 LPA' },
    ],
    keySalaryFactors: [
      'PSU vs Private Core vs IT Crossover roles',
      'Specialization in VLSI Semiconductor design vs field electrical maintenance',
      'GATE rank performance',
    ],
    topCountriesAbroad: ['Germany', 'United States', 'Taiwan', 'Japan', 'Netherlands'],
    requiredExamsAbroad: ['GRE', 'TOEFL / IELTS', 'FE (Fundamentals of Engineering Exam) - USA'],
    licensingAbroad: 'Passing FE & PE (Professional Engineer) exam in the US allows sign-off on public power infrastructure projects.',
    educationEquivalency: 'Indian 4-year B.Tech EE recognized globally under Washington Accord for international licensing.',
    salaryAbroadComparison: [
      { country: 'United States', avgSalary: '$120,000 - $180,000 USD', visaEase: 'Moderate' },
      { country: 'Germany', avgSalary: '€68,000 - €95,000 EUR', visaEase: 'Very High' },
      { country: 'Taiwan', avgSalary: '$85,000 - $130,000 USD (Semiconductor Fab)', visaEase: 'High' },
      { country: 'Japan', avgSalary: '¥8,000,000 - ¥12,000,000 JPY', visaEase: 'High' },
    ],
    immigrationRelocationPath: 'Pursue M.Sc in Power/VLSI in Germany (No tuition fees) -> EU Blue Card -> Permanent Residency within 21 months.',
    advantages: [
      'Direct Gateway to Prestigious Government PSU Careers with High Job Security',
      'Central Role in Global Clean Energy & EV Transition',
      'High Demand in Booming Semiconductor Chip Industry',
    ],
    disadvantages: [
      'Lower Starting Pay in Local Non-Tier-1 Private Core Companies (₹3-5 LPA)',
      'Physical Hazards associated with High-Voltage Infrastructure',
      'High Mathematical & Physical Rigor Required',
    ],
    keyChallenges: [
      'Adapting traditional electrical networks to intermittent renewable energy and smart grid dynamics',
      'Managing thermal dissipation in miniaturized high-power EV electronics',
    ],
    workLifeBalanceRating: 8,
    typicalWorkingHours: '40 - 48 Hours / Week (PSUs maintain excellent work-life balance)',
    stressLevel: 'Moderate (High during grid fault incidents or power plant outages)',
    jobSecurityRating: 10,
    competitionLevel: 'Extremely High for PSU recruitment via GATE (Top 0.5% candidates selected)',
    careerGrowthVelocity: 'Steady, structured progression in PSUs; Fast in Semiconductor MNCs',
    futureDemandOutlook: 'Accelerating Growth. India\'s $10B Semiconductor Manufacturing Mission and national EV mandate guarantee immense core demand through 2045.',
    aiAutomationImpact: 'AI assists in grid load forecasting and automated PCB routing, but high-voltage physical installation and hardware testing remain human-dependent.',
    aiReplacementRiskLevel: 'Very Low Risk (5%). Physical hardware manufacturing, circuit fabrication, and high-voltage maintenance cannot be automated by software.',
    emergingOpportunities: [
      'Next-Gen Electric Vehicle Solid-State Battery Systems',
      'Green Hydrogen Electrolyzer Power Supplies',
      'Commercial Semiconductor Fabrication Plants in India',
    ],
    emergingSpecializations: [
      'EV Battery Management Systems (BMS) Architect',
      'Wide-Bandgap Semiconductor Specialist',
      'Smart Grid Cyber-Physical Security Engineer',
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // ==========================================
  // PROFILE 5: MECHANICAL & AEROSPACE SYSTEMS ENGINEER (India Home -> ISRO / Automotive R&D / Global Robotics)
  // ==========================================
  {
    id: 'report_clx_98471208',
    intakeId: 'intake_clx_0019288',
    careerName: 'Mechanical & Aerospace Systems Engineer',
    careerOverview: `A Mechanical Engineer in India applies thermodynamics, fluid mechanics, materials science, and structural analysis to design, manufacture, and maintain mechanical systems. Roles range from designing space launch vehicles at ISRO, high-speed rail systems, and defense machinery to engineering modern EV chassis, HVAC systems, and industrial robotics.`,
    whatProfessionalDoes: `• Design mechanical components, sub-assemblies, and propulsion structures using CAD tools (CATIA, SOLIDWORKS).
• Perform Finite Element Analysis (FEA) and Computational Fluid Dynamics (CFD) simulations using ANSYS / HyperMesh.
• Manage automated manufacturing lines, CNC machining, additive manufacturing (3D printing), and robotics.
• Conduct vibration, stress, thermal, and crashworthiness testing for automotive and aerospace components.`,
    whyChooseThisCareer: `The ultimate evergreen foundation of all engineering. Offers physical creation satisfaction, access to aerospace research agencies (ISRO/DRDO), and leadership roles across heavy manufacturing and robotics.`,
    whoIsSuitableFor: `Individuals with strong spatial visualization, passion for machinery, engines, robotics, structural design, and real-world physical problem solving.`,
    requiredSkills: [
      '3D CAD Modeling (CATIA, SolidWorks, PTC Creo)',
      'FEA & CFD Simulation (ANSYS, HyperMesh, Abaqus)',
      'Thermodynamics & Heat Transfer Analysis',
      'Robotics, Mechatronics, & Hydraulics',
      'Design for Manufacturing & Assembly (DFMA)',
    ],
    importantSubjects: [
      'Thermodynamics & Fluid Mechanics',
      'Strength of Materials & Machine Design',
      'Manufacturing Processes & CAD/CAM',
      'Heat & Mass Transfer',
    ],
    workEnvironmentDesc: 'Automotive R&D centers, space launch facilities, defense manufacturing plants, heavy machinery assembly bays, or engineering design studios.',
    typicalDayLife: `• 08:30 AM: Review CFD simulation results for aerodynamic drag on a new EV chassis model.
• 11:00 AM: Structural stress testing on a composite aerospace bracket using ANSYS FEA.
• 02:00 PM: On-site shop floor inspection of robotic welding accuracy on automated assembly line.
• 04:30 PM: Design review meeting with thermal management team regarding liquid cooling loops.`,
    class10Requirements: 'Minimum 60%+ in Science and Mathematics.',
    class11_12Stream: 'Science Stream with Physics, Chemistry, and Advanced Mathematics (PCM).',
    subjectsRequired: ['Physics', 'Mathematics', 'Chemistry', 'English'],
    minQualification: 'BACHELORS',
    ageLimit: 'No limit in private industry. ISRO Scientist age limit: 28-35 years; GATE PSU age limit: 28-30 years.',
    nationalityEligibility: 'Indian National (Mandatory for ISRO, DRDO, and Defense PSUs).',
    medicalRequirements: 'Standard physical fitness for shop floor inspection and field operations.',
    courseOptions: [
      'B.Tech / B.E. in Mechanical Engineering / Aerospace Engineering',
      'B.Tech in Mechatronics / Automotive Engineering',
      'M.Tech in Thermal Engineering / CAD-CAM / Robotics',
    ],
    courseDuration: '4 Years (B.Tech / B.E.) + Optional 2 Years (M.Tech)',
    degreeRequired: 'B.Tech / B.E. in Mechanical or Aerospace Engineering',
    entranceExams: ['JEE Main', 'JEE Advanced', 'GATE (Mechanical - ME)', 'ISRO Centralised Recruitment (ICRB)', 'State CETs'],
    nationalExams: ['JEE Main', 'JEE Advanced', 'GATE ME Paper'],
    stateExams: ['MHT-CET', 'KCET', 'WBJEE', 'TNEA'],
    universityExams: ['BITSAT', 'VITEEE', 'MET Manipal'],
    examEligibility: 'Class 12 PCM with minimum 75% aggregate score for IITs/NITs (60% for private universities).',
    examPattern: 'JEE Main (CBT 3 Hrs) | GATE ME: 65 Questions (100 Marks) testing Engineering Mechanics, SOM, Thermo, Manufacturing.',
    examSubjects: ['Applied Mechanics & Design', 'Fluid Mechanics & Thermal Sciences', 'Materials & Manufacturing', 'Engineering Mathematics'],
    numberOfQuestions: 65,
    markingScheme: '+1 or +2 marks for correct answer, negative marking for incorrect MCQs in GATE.',
    examFrequency: 'GATE held once annually in February.',
    applicationProcess: 'Apply online for GATE (GOAPS portal) or ISRO ICRB recruitment portal; appear for written examination and personal technical interview.',
    applicationFees: '₹1,800 General for GATE; ₹900 Reserved.',
    importantDates: 'GATE Exam (Feb); ISRO ICRB Notification (Varies based on vacancy).',
    prepStrategy: 'Focus on concept clarity in Strength of Materials, Thermodynamics, and Production Engineering. Solve 20 years of GATE ME previous papers.',
    recommendedBooks: [
      'Strength of Materials by SK Mondal / Ramamrutham',
      'Engineering Thermodynamics by PK Nag',
      'Fluid Mechanics by RK Bansal',
      'Design of Machine Elements by VB Bhandari',
    ],
    prepTimeline: '12 to 24 Months.',
    admissionProcess: 'PSU direct selection via GATE score and interview; ISRO selection via written test and interview.',
    counsellingProcess: 'JoSAA for B.Tech; COAP for M.Tech seats in IITs.',
    quotaReservations: 'Standard Govt Reservations: SC (15%), ST (7.5%), OBC-NCL (27%), EWS (10%), PwD (5%).',
    topGovtColleges: [
      'Indian Institute of Space Science and Technology (IIST), Thiruvananthapuram (Direct ISRO pipeline)',
      'Indian Institute of Technology (IIT) Madras, Bombay, Kharagpur, Kanpur',
      'National Institute of Technology (NIT) Trichy, Surathkal',
    ],
    topPrivateColleges: [
      'BITS Pilani (Pilani Campus)',
      'PSG College of Technology, Coimbatore',
      'Manipal Institute of Technology (MIT), Manipal',
    ],
    collegeSelectionGuide: 'Target IIST for direct absorption into ISRO as Scientist-SC. Target top IITs for international aerospace R&D recruitment (Airbus, Boeing) and top PSUs (HAL, BARC, BHEL).',
    expectedCutoffs: 'GATE ME Score > 80/100 for top PSU selection call in General category.',
    feeStructure: 'IITs/NITs: ₹8 Lakhs - ₹10 Lakhs 4-year total fee | IIST offers full government tuition funding for top performers.',
    availableScholarships: [
      'ISRO Assistantship Grant at IIST',
      'MHRD M.Tech GATE Scholarship (₹12,400/month)',
      'AICTE National Doctoral Fellowship',
    ],
    stepByStepRoadmap: `Step 1: Graduate with B.Tech in Mechanical Engineering with CAD/CAE hands-on project exposure.
Step 2: Crack GATE Exam (ME) or ISRO Scientist Entrance Test.
Step 3: Join ISRO / DRDO as Scientist-SC OR join Defense PSU (HAL, BEL) OR Automotive R&D center.
Step 4: Specialize in FEA, crash simulation, propulsion systems, or robotics (0-3 Years).
Step 5: Advance to Lead Simulation Engineer / R&D Manager (4-8 Years).
Step 6: Become Chief Mechanical Engineer / Director of R&D / Project Director Space Missions (10+ Years).`,
    internshipRequirements: 'Mandatory 6-8 week industrial internship at an automotive manufacturing plant, heavy engineering plant, or aerospace lab.',
    licensingRegistration: 'Chartered Engineer (CEng) status via Institution of Engineers India (IEI) for industrial sign-offs.',
    entryLevelRoles: ['Scientist-SC (ISRO/DRDO)', 'Automotive Design Engineer', 'Graduate Engineer Trainee (GET)', 'Thermal Engineer'],
    midLevelRoles: ['Senior R&D Engineer', 'Lead FEA / CAE Simulation Specialist', 'Production Manager'],
    seniorLevelRoles: ['Chief Mechanical Engineer', 'Mission Director (Space Missions)', 'VP of Vehicle Engineering / Plant Operations'],
    specializations: ['Aerospace Propulsion & Structures', 'Automotive CAE / Crashworthiness / NVH', 'Robotics & Industrial Mechatronics', 'Thermal Management Systems'],
    superSpecializations: ['Cryogenic Rocket Engine Design', 'Hypersonic Aerodynamics', 'Additive Manufacturing for Space Payloads'],
    higherEducationPaths: ['M.Tech in Aerospace / Thermal Engineering', 'MS in Mechanical / Robotics in Germany/USA', 'Ph.D. in Computational Mechanics'],
    alternativeCareerPaths: ['Operations Management (MBA at IIMs)', 'Data Analytics / Engineering Consulting', 'Intellectual Property & Patent Examiner'],
    govtJobOpportunities: 'ISRO, DRDO, BARC, Hindustan Aeronautics Limited (HAL), Bharat Heavy Electricals (BHEL), Indian Railways (IES ESE Mechanical Officers).',
    privateJobOpportunities: 'Automotive OEMs (Tata Motors, Mahindra, Maruti Suzuki), Aerospace R&D hubs (Boeing India, Airbus India), Heavy Machinery (L&T, Caterpillar).',
    selfEmploymentOptions: 'Mechanical Product Design Consultancy, CNC Machining Workshop, Automation System Integration Agency.',
    hiringIndustries: ['Aerospace & Defense Manufacturing', 'Automotive & Electric Vehicles', 'Industrial Robotics & Heavy Equipment', 'Energy & HVAC Engineering'],
    topGlobalEmployers: [
      'ISRO (Indian Space Research Organisation)',
      'DRDO',
      'Boeing / Airbus R&D India',
      'Tata Motors',
      'Larsen & Toubro (L&T)',
      'Mahindra & Mahindra',
      'Tesla / SpaceX (Global post foreign degree)',
    ],
    primeWorkLocations: ['Bengaluru', 'Pune', 'Hyderabad', 'Thiruvananthapuram', 'Stuttgart / Munich (Germany)', 'Detroit (USA)'],
    homeVsAbroadOverview: 'India offers high-prestige space and defense roles (ISRO/DRDO). Overseas, Germany (TU9 Universities) and USA are the ultimate global destinations for automotive and aerospace R&D.',
    freelanceOpportunities: 'Outsourced 3D CAD Modeling, FEA Stress Analysis Contracts, 3D Printing Prototype Bureau Services.',
    startingSalaryRange: '₹6.0 - ₹14.0 Lakhs Per Annum (ISRO Scientist / Top Automotive R&D / PSUs)',
    averageSalary: '₹14.0 - ₹25.0 Lakhs Per Annum (Mid-Level Mechanical / CAE Lead)',
    experiencedSalary: '₹28.0 - ₹55.0 Lakhs Per Annum (Senior R&D Manager / Plant Head)',
    highestPotentialEarnings: '₹80.0 Lakhs - ₹2.0+ Crores Per Annum (VP Automotive Engineering / Global Aerospace Lead)',
    govtSalaryScale: '₹10.0 - ₹18.0 LPA (Scientist-SC scale Level 10 + Central Govt Housing, Healthcare, Allowances)',
    privateSectorSalary: '₹5.0 - ₹60.0+ LPA',
    selfEmploymentEarnings: '₹8.0 - ₹35.0 LPA (Component Manufacturing / Engineering Services)',
    salaryByExperience: [
      { stage: 'Entry-Level (0-2 yrs)', range: '₹6 - ₹12 LPA (Core R&D / PSU)' },
      { stage: 'Mid-Career (3-6 yrs)', range: '₹14 - ₹22 LPA' },
      { stage: 'Senior (7-10 yrs)', range: '₹25 - ₹42 LPA' },
      { stage: 'Principal / Executive (10+ yrs)', range: '₹50 - ₹1.5+ Crores' },
    ],
    salaryBySpecialization: [
      { specialization: 'Aerospace Systems & Propulsion', avgSalary: '₹24 LPA' },
      { specialization: 'CAE Crash & Structural Simulation', avgSalary: '₹20 LPA' },
      { specialization: 'Robotics & Automated Manufacturing', avgSalary: '₹18 LPA' },
      { specialization: 'HVAC & General Plant Maintenance', avgSalary: '₹12 LPA' },
    ],
    keySalaryFactors: [
      'Govt R&D (ISRO/DRDO) vs Core Private R&D vs Local Shop Floor Production',
      'Mastery of CAE Simulation tools (ANSYS/HyperMesh) vs manual drafting',
      'Master\'s degree from IITs or TU9 Germany',
    ],
    topCountriesAbroad: ['Germany', 'United States', 'Sweden', 'Japan', 'France'],
    requiredExamsAbroad: ['GRE', 'TOEFL / IELTS', 'German Language Certification (TestDaF / Goethe B2/C1)'],
    licensingAbroad: 'PE (Professional Engineer) license in US/Canada; FE Exam completion.',
    educationEquivalency: 'Indian 4-year B.Tech ME degree recognized under Washington Accord for international master\'s programs.',
    salaryAbroadComparison: [
      { country: 'Germany (Munich/Stuttgart)', avgSalary: '€65,000 - €90,000 EUR', visaEase: 'Very High' },
      { country: 'United States (Detroit/California)', avgSalary: '$110,000 - $165,000 USD', visaEase: 'Moderate' },
      { country: 'Sweden (Gothenburg - Automotive)', avgSalary: '480,000 - 650,000 SEK', visaEase: 'High' },
      { country: 'Japan', avgSalary: '¥7,500,000 - ¥11,000,000 JPY', visaEase: 'High' },
    ],
    immigrationRelocationPath: 'Enroll in Tuition-Free MS in Mechanical/Automotive Engineering in Germany -> 18-Month Job-Seeker Visa -> EU Blue Card.',
    advantages: [
      'Direct Contribution to Landmark National Achievements (ISRO Space Missions & Defense)',
      'Tangible Real-World Engineering Satisfaction (Building physical vehicles & machinery)',
      'Clear, Tuition-Free Immigration Pathway to Germany\'s Automotive Hubs',
    ],
    disadvantages: [
      'Lower Starting Salaries in Local Private Production Shop Floors (₹3-4 LPA)',
      'Capital-Intensive Field (Harder to start independent companies compared to software)',
      'Work Environment can involve noise, heat, and heavy machinery safety risks',
    ],
    keyChallenges: [
      'Navigating the transition from Internal Combustion Engines (ICE) to EV powertrains',
      'Balancing structural safety margins with strict lightweighting requirements',
    ],
    workLifeBalanceRating: 7,
    typicalWorkingHours: '42 - 50 Hours / Week',
    stressLevel: 'Moderate (High during physical testing or launch countdowns)',
    jobSecurityRating: 9,
    competitionLevel: 'Fierce for ISRO / GATE PSU seats; High for top automotive R&D labs',
    careerGrowthVelocity: 'Steady, experience-driven maturity',
    futureDemandOutlook: 'Sustained Core Growth. Driven by EV manufacturing, industrial automation, defense indigenization (Make in India), and commercial space exploration.',
    aiAutomationImpact: 'AI accelerates Generative CAD Design and topology optimization. Physical manufacturing execution, structural testing, and assembly remain human-led.',
    aiReplacementRiskLevel: 'Very Low Risk (5%). Physical testing, manufacturing robotics calibration, and mechanical assembly cannot be replaced by AI.',
    emergingOpportunities: [
      'Private Commercial Space Tech Payloads (Agnikul, Skyroot Aerospace)',
      'Generative Design & Additive Manufacturing (3D Metal Printing)',
      'Autonomous Industrial Mobile Robots (AMRs)',
    ],
    emergingSpecializations: [
      'EV Thermal Management Specialist',
      'Spacecraft Structural Composite Engineer',
      'Mechatronic Robotics Systems Architect',
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // ==========================================
  // PROFILE 6: AI & CLOUD SYSTEMS ARCHITECT (Original Global Profile)
  // ==========================================
  {
    id: 'report_clx_98471203',
    intakeId: 'intake_clx_0019283',
    careerName: 'Artificial Intelligence & Cloud Systems Architect',
    careerOverview: `An AI & Cloud Systems Architect designs, engineers, and governs large-scale artificial intelligence ecosystems integrated into global enterprise cloud infrastructures (AWS, GCP, Azure). They bridge advanced machine learning models with distributed backend networks, ensuring systems are fault-tolerant, secure, cost-effective, and highly performant under massive traffic loads.`,
    whatProfessionalDoes: `• Architect end-to-end Machine Learning pipelines and enterprise cloud deployment infrastructures.
• Select optimal database, compute, and model inference configurations (e.g., LLM fine-tuning, vector databases, serverless microservices).
• Establish data privacy, zero-trust security boundaries, and ethical AI governance standards.
• Audit system latency, optimize GPU compute expenditures, and manage disaster recovery protocols.`,
    whyChooseThisCareer: `This field represents the apex of technical strategy, combining top-tier financial rewards with unmatched global mobility and immunity to AI automated replacement (as architects are the creators and supervisors of AI automation).`,
    whoIsSuitableFor: `Suitable for logical thinkers, strong analytical problem solvers, and individuals fascinated by complex computer systems, mathematical modeling, and distributed software engineering.`,
    requiredSkills: [
      'Distributed Systems Design',
      'Python & C++ Optimization',
      'PyTorch & TensorFlow',
      'Cloud Platforms (AWS/GCP/Azure)',
      'Kubernetes & Docker Orchestration',
      'Vector Databases (Pinecone, Qdrant)',
      'System Cost Governance',
    ],
    importantSubjects: [
      'Advanced Mathematics (Linear Algebra, Calculus)',
      'Computer Science & Algorithms',
      'Data Structures & Probability',
      'Physics / Logic',
    ],
    workEnvironmentDesc: 'High-tech corporate headquarters, modern innovation labs, or 100% remote asynchronous global setups.',
    typicalDayLife: `• 09:00 AM: System status audit and cloud cost anomaly review.
• 10:30 AM: Architecture design review session with senior data engineering leads.
• 01:00 PM: Deep focus time: benchmark LLM inference latencies on Kubernetes GPU clusters.
• 03:30 PM: Security & compliance sync for international cross-border data transfer regulations.`,
    class10Requirements: 'Strong foundational performance in Mathematics and Science (Minimum 80%+ or A Grade equivalent).',
    class11_12Stream: 'Physical Sciences & Engineering Track (Physics, Chemistry, Advanced Mathematics, Computer Science).',
    subjectsRequired: ['Mathematics (Calculus/Statistics)', 'Physics', 'Computer Science / Programming Basics'],
    minQualification: 'BACHELORS',
    ageLimit: 'No maximum age limit. Minimum age typically 17+ for university entrance.',
    nationalityEligibility: 'Open globally across domestic and international institutions.',
    medicalRequirements: 'Standard ergonomics; no specialized physical medical clearances required.',
    courseOptions: [
      'B.Sc / B.Tech in Computer Science & Engineering',
      'B.Sc in Artificial Intelligence & Data Science',
      'M.Sc / M.Tech in Distributed Systems or Machine Learning',
    ],
    courseDuration: '4 Years (Undergraduate Degree) + Optional 2 Years (Master\'s Degree)',
    degreeRequired: 'Bachelor of Science (B.Sc / B.Tech / B.E.) in Computer Science or Software Engineering',
    entranceExams: ['SAT / ACT (USA)', 'JEE Advanced (India)', 'A-Levels / STEP (UK)', 'GRE (Graduate Studies)'],
    nationalExams: ['SAT Computer-Based Test', 'JEE Main & Advanced', 'Gaokao (China Science Stream)'],
    stateExams: ['State Engineering CETs', 'Regional University Eligibility Assessments'],
    universityExams: ['MIT / Stanford Holistic Evaluation', 'Imperial / Cambridge Mathematics Assessment (MAT/STEP)'],
    examEligibility: 'Successful completion of High School / Grade 12 diploma with Physics, Chemistry, and Advanced Mathematics.',
    examPattern: 'Multiple-choice and analytical problem-solving tests assessing quantitative aptitude, logical reasoning, and core physics/math concepts.',
    examSubjects: ['Mathematics (Calculus, Probability, Vectors)', 'Physics (Mechanics, Electromagnetism)', 'Logic & Code Comprehension'],
    numberOfQuestions: 75,
    markingScheme: '+4 for correct response, -1 for incorrect penalty (Standard Engineering Pattern)',
    examFrequency: 'Twice Annually (Spring & Autumn cycles depending on region)',
    applicationProcess: 'Online application submission via Common App, UCAS, or Centralised Entrance Portals including official transcripts, SOP, and recommendation letters.',
    applicationFees: '$80 - $150 USD per university portal',
    importantDates: 'November 1 (Early Action Deadlines); January 15 (Regular Admission Cutoffs)',
    prepStrategy: 'Focus on mastering core calculus, linear algebra, and data structures. Solve 10+ years of past quantitative paper sets under strict timed conditions.',
    recommendedBooks: [
      'Introduction to Algorithms (CLRS)',
      'Designing Data-Intensive Applications by Martin Kleppmann',
      'Deep Learning by Ian Goodfellow',
    ],
    prepTimeline: '12 to 18 Months of dedicated preparation alongside high school coursework.',
    admissionProcess: 'Merit-based entrance exam scores combined with academic transcripts, portfolio projects (GitHub), and technical interviews.',
    counsellingProcess: 'Centralised online seat allocation and merit-tier university selection counseling.',
    quotaReservations: 'Merit, international student allocations, and regional equity quotas as applicable.',
    topGovtColleges: [
      'Massachusetts Institute of Technology (MIT), USA',
      'University of Cambridge, UK',
      'Indian Institute of Technology (IIT Bombay/Delhi), India',
      'ETH Zurich, Switzerland',
      'National University of Singapore (NUS), Singapore',
    ],
    topPrivateColleges: [
      'Stanford University, USA',
      'Carnegie Mellon University (CMU), USA',
      'Imperial College London, UK',
    ],
    collegeSelectionGuide: 'Prioritize institutions with active research labs in distributed systems, dedicated GPU clusters, strong career placement networks, and industry internships.',
    expectedCutoffs: '98th percentile or higher in standardized entrance assessments.',
    feeStructure: 'Public/State: $10,000 - $25,000/yr | Top Private International: $45,000 - $65,000/yr',
    availableScholarships: [
      'Global STEM Leadership Grants',
      'Fulbright Foreign Student Program',
      'University Merit Scholarships (up to 100% tuition waiver)',
    ],
    stepByStepRoadmap: `Step 1: Complete High School with Mathematics & Science focus.
Step 2: Graduate with B.Sc in Computer Science (Maintain GPA > 3.5/4.0).
Step 3: Secure summer engineering internships at software or cloud providers.
Step 4: Enter industry as Junior Backend / Cloud Engineer (0-2 Years).
Step 5: Transition to Mid-Level Infrastructure / MLOps Engineer (3-5 Years).
Step 6: Attain Cloud Systems Architect / Principal AI Engineer leadership (6+ Years).`,
    internshipRequirements: 'Completion of two 12-week industry engineering internships during undergraduate studies.',
    licensingRegistration: 'AWS Certified Solutions Architect Professional / Google Cloud Professional Cloud Architect credentials highly valued.',
    entryLevelRoles: ['Junior Software Engineer', 'Associate Cloud Engineer', 'Data Pipeline Developer'],
    midLevelRoles: ['Senior Backend Engineer', 'MLOps Engineer', 'Cloud Infrastructure Specialist'],
    seniorLevelRoles: ['Principal AI Architect', 'VP of Infrastructure Engineering', 'Chief Technology Officer (CTO)'],
    specializations: ['Distributed Systems', 'Generative AI Infrastructure', 'High-Performance GPU Compute', 'Cloud Security'],
    superSpecializations: ['Quantum Cloud Computing', 'Edge AI Micro-Architectures', 'Zero-Knowledge Cryptographic Cloud'],
    higherEducationPaths: ['Ph.D. in Distributed Computing', 'M.Sc in Machine Learning Systems', 'Executive MBA'],
    alternativeCareerPaths: ['Quantitative Developer in High-Frequency Trading', 'Tech Founder / Startup CEO', 'Technical Venture Capitalist'],
    govtJobOpportunities: 'High-demand in Defense, Space Research Organizations (NASA/ESA), and Cyber Security Agencies.',
    privateJobOpportunities: 'Massive demand across Big Tech, Fintech enterprise conglomerates, HealthTech, and AI labs (OpenAI, Anthropic).',
    selfEmploymentOptions: 'High-value specialized Cloud & AI Architecture Consulting ($200 - $500 / hour rates).',
    hiringIndustries: ['Big Tech & Cloud Platforms', 'Quantitative Finance & Investment Banking', 'Autonomous Vehicles & Defense', 'Healthcare & Genomics'],
    topGlobalEmployers: ['Google / DeepMind', 'Amazon Web Services (AWS)', 'Microsoft', 'NVIDIA', 'Meta', 'OpenAI'],
    primeWorkLocations: ['Silicon Valley / San Francisco', 'Seattle', 'London', 'Zurich', 'Singapore', 'Bengaluru'],
    homeVsAbroadOverview: 'Extremely flexible. Local domestic tech hubs offer strong compensation, while international hubs provide top 1% global earnings.',
    freelanceOpportunities: 'Contract AI Infrastructure Audit and Security Consulting.',
    startingSalaryRange: '$90,000 - $130,000 USD / Year',
    averageSalary: '$165,000 - $220,000 USD / Year',
    experiencedSalary: '$280,000 - $420,000 USD / Year',
    highestPotentialEarnings: '$600,000 - $1,200,000+ USD / Year (Including Stock/Equity Grants)',
    govtSalaryScale: '$80,000 - $140,000 USD / Year + Pension & Full Benefits',
    privateSectorSalary: '$120,000 - $800,000+ USD / Year',
    selfEmploymentEarnings: '$150,000 - $500,000 USD / Year',
    salaryByExperience: [
      { stage: 'Entry-Level (0-2 yrs)', range: '$90,000 - $130,000' },
      { stage: 'Mid-Career (3-6 yrs)', range: '$140,000 - $220,000' },
      { stage: 'Senior (7-10 yrs)', range: '$230,000 - $380,000' },
      { stage: 'Principal / Executive (10+ yrs)', range: '$400,000 - $1,000,000+' },
    ],
    salaryBySpecialization: [
      { specialization: 'Generative AI Systems Architect', avgSalary: '$260,000 USD' },
      { specialization: 'Cloud Security & Zero Trust Architect', avgSalary: '$225,000 USD' },
      { specialization: 'Fintech High-Frequency Systems Architect', avgSalary: '$310,000 USD' },
      { specialization: 'General Infrastructure Architect', avgSalary: '$185,000 USD' },
    ],
    keySalaryFactors: [
      'Geographic Location (Silicon Valley/NY vs Remote)',
      'Equity/Stock Grant Options (RSUs)',
      'Mastery of GPU Acceleration Infrastructure',
      'Scale of Distributed Systems Managed',
    ],
    topCountriesAbroad: ['United States', 'Switzerland', 'United Kingdom', 'Canada', 'Singapore', 'Germany'],
    requiredExamsAbroad: ['TOEFL / IELTS (English Language)', 'GRE (For Post-Graduate Entry)'],
    licensingAbroad: 'No restrictive state medical or legal licensing required. Industry certification (AWS/GCP) recognized globally.',
    educationEquivalency: 'Standard B.Sc degree in Computer Science recognized under Washington Accord across all major OECD countries.',
    salaryAbroadComparison: [
      { country: 'United States', avgSalary: '$210,000 USD', visaEase: 'Moderate' },
      { country: 'Switzerland', avgSalary: '$190,000 USD', visaEase: 'Challenging' },
      { country: 'United Kingdom', avgSalary: '£110,000 GBP', visaEase: 'High' },
      { country: 'Singapore', avgSalary: '$160,000 SGD', visaEase: 'High' },
    ],
    immigrationRelocationPath: 'H-1B / O-1 Visa (USA), Global Talent Visa (UK), Employment Pass (Singapore), Critical Skills Visa (EU).',
    advantages: [
      'Top 1% Global Earning Potential',
      'Unmatched Remote Work Flexibility & Geographic Freedom',
      'High Industry Prestige & Strategic Influence',
      'Continuous Learning with Frontier Technologies',
    ],
    disadvantages: [
      'High Cognitive Load & Need for Continuous Skill Upgrades',
      'Occasional Critical System Outage Stress (On-Call Rotations)',
      'Sedentary Screen-Based Work Environment',
    ],
    keyChallenges: [
      'Rapidly Evolving Frameworks Becoming Obsolete Every 3 Years',
      'Managing High Cloud Infrastructure Operating Expenditures',
    ],
    workLifeBalanceRating: 8,
    typicalWorkingHours: '40 - 45 Hours / Week (Flexible)',
    stressLevel: 'Moderate to High during active deployment periods',
    jobSecurityRating: 10,
    competitionLevel: 'High for Top-Tier Companies; Moderate elsewhere due to talent shortage',
    careerGrowthVelocity: 'Rapid (Promotion cycles every 1.5 - 3 years)',
    futureDemandOutlook: 'Extraordinarily High. Demand for specialists capable of designing scalable AI cloud architecture is projected to grow 32% annually through 2035.',
    aiAutomationImpact: 'Constructive. AI enhances coding efficiency, but architects are required to design, supervise, and secure the AI models themselves.',
    aiReplacementRiskLevel: 'Extremely Low Risk (0-5%). High human judgment, systemic reasoning, and creative engineering cannot be automated.',
    emergingOpportunities: [
      'Sovereign Cloud AI Governance',
      'Edge Compute for Autonomous Drones & Vehicles',
      'Neuromorphic Computing Infrastructure',
    ],
    emergingSpecializations: [
      'AI Cloud Sustainability & Green Energy Computing',
      'Quantum Cloud Architecture',
      'Decentralized AI Networks',
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

];
